In [1]:
#importing libraries
import selenium
from selenium import webdriver
import pandas as pd
from selenium.webdriver.common.by import By
import warnings
warnings.filterwarnings('ignore')
import time
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import re

In [129]:
#Connecting to the driver
driver=webdriver.Chrome(r'C:\Users\Admin\Downloads\chromedriver_win32\chromedriver.exe')

#Maximizing the automated
driver.maximize_window()

#opening the wikipedia website on automated chrome window
url='https://www.cars24.com/'
driver.get(url)

In [69]:
#clicking on city
city=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p')
city.click()

In [70]:
#clicking on select manually option
manually=driver.find_element(By.XPATH,'/html/body/div[1]/div[8]/div/div/div/div[2]/div[2]/button')
manually.click()

In [72]:
#clicking on city new delhi
delhi=driver.find_element(By.XPATH,'/html/body/div[1]/div[8]/div/div/div/div/div[2]/ul/li[1]')
delhi.click()

In [73]:
#clicking on view all cars options
view_all_cars=driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div/div[2]/div/div[2]/button[1]')
view_all_cars.click()

In [20]:
#scrapping Brand
brand=[]
try:
    brand_tag=driver.find_elements(By.XPATH,'//h3[@class="_3FpCg"]')
    for j in brand_tag:
        brand.append(j.text.split(' ')[1])
except NoSuchElementException : #handling no such element exception
    brand.append('-')

In [21]:
#Number of data scrapped
len(brand)

1080

In [27]:
#printing brand
brand

['Maruti',
 'KIA',
 'Maruti',
 'KIA',
 'Hyundai',
 'Renault',
 'Hyundai',
 'Hyundai',
 'Maruti',
 'Maruti',
 'KIA',
 'Maruti',
 'KIA',
 'Maruti',
 'KIA',
 'Honda',
 'Hyundai',
 'KIA',
 'KIA',
 'Maruti',
 'Maruti',
 'KIA',
 'Maruti',
 'Maruti',
 'Skoda',
 'Honda',
 'KIA',
 'Maruti',
 'KIA',
 'KIA',
 'Maruti',
 'KIA',
 'Hyundai',
 'KIA',
 'Toyota',
 'Renault',
 'Hyundai',
 'Maruti',
 'KIA',
 'Maruti',
 'Hyundai',
 'KIA',
 'Renault',
 'Hyundai',
 'Renault',
 'Toyota',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Tata',
 'KIA',
 'Renault',
 'KIA',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Hyundai',
 'KIA',
 'Maruti',
 'Honda',
 'Renault',
 'Hyundai',
 'Hyundai',
 'Renault',
 'Renault',
 'Renault',
 'Hyundai',
 'Hyundai',
 'Renault',
 'Hyundai',
 'Renault',
 'Maruti',
 'Datsun',
 'Maruti',
 'Renault',
 'Datsun',
 'Datsun',
 'Ford',
 'Hyundai',
 'Toyota',
 'Maruti',
 'Maruti',
 'Maruti',
 'Honda',
 'Honda',
 'Maruti',
 'Skoda',
 'Maruti',
 'Maruti',
 'Toyota',
 'Renault',
 'Maruti',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Nissan',
 'Maruti',
 'Hyundai',
 'Hyundai',
 'Hyundai',
 'Renault',
 'Honda',
 'Hyundai',
 'Renault',
 'Hyundai',
 'Jeep',
 'Renault',
 'Tata',
 'Hyundai',
 'Renault',
 'Mahindra',
 'Maruti',
 'Maruti',
 'Maruti',
 'Honda',
 'Maruti',
 'Tata',
 'Maruti',
 'Maruti',
 'Honda',
 'KIA',
 'Hyundai',
 'Tata',
 'Tata',
 'Honda',
 'Maruti',
 'Maruti',
 'Honda',
 'Maruti',
 'Maruti',
 'Ford',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Honda',
 'Maruti',
 'Maruti',
 'Maruti',
 'Hyundai',
 'MARUTI',
 'Tata',
 'Maruti',
 'Renault',
 'Honda',
 'Maruti',
 'Tata',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Honda',
 'Honda',
 'Maruti',
 'Honda',
 'Honda',
 'Maruti',
 'Maruti',
 'Honda',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Honda',
 'Hyundai',
 'Honda',
 'Honda',
 'Honda',
 'Maruti',
 'Honda',
 'Toyota',
 'Maruti',
 'Maruti',
 'Honda',
 'Maruti',
 'Mahindra',
 'Maruti',
 'Hyundai',
 'Toyota',
 'Tata',
 'Hyundai',
 'Maruti',
 'Mahindra',
 'Honda',
 'Tata',
 'Honda',
 'Honda',
 'Hyundai',
 'Jeep',
 'Toyota',
 'Hyundai',
 'Hyundai',
 'Tata',
 'Maruti',
 'Maruti',
 'Honda',
 'Hyundai',
 'Maruti',
 'Mahindra',
 'Maruti',
 'Honda',
 'Maruti',
 'Honda',
 'Maruti',
 'Tata',
 'Honda',
 'Honda',
 'Honda',
 'Hyundai',
 'Tata',
 'Honda',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Honda',
 'Tata',
 'Honda',
 'Hyundai',
 'Maruti',
 'Honda',
 'Hyundai',
 'Maruti',
 'Tata',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Tata',
 'Hyundai',
 'Renault',
 'Skoda',
 'Honda',
 'Tata',
 'Maruti',
 'Honda',
 'Hyundai',
 'Honda',
 'Maruti',
 'Maruti',
 'Tata',
 'Honda',
 'Maruti',
 'Honda',
 'Maruti',
 'Tata',
 'Hyundai',
 'Maruti',
 'Honda',
 'Hyundai',
 'Renault',
 'Honda',
 'Skoda',
 'Hyundai',
 'Honda',
 'Datsun',
 'Renault',
 'Maruti',
 'Honda',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Honda',
 'Hyundai',
 'Hyundai',
 'Hyundai',
 'Hyundai',
 'Renault',
 'Hyundai',
 'Hyundai',
 'Honda',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Ford',
 'Renault',
 'Renault',
 'Hyundai',
 'Maruti',
 'Honda',
 'Honda',
 'Honda',
 'Honda',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Toyota',
 'Honda',
 'Hyundai',
 'Maruti',
 'Toyota',
 'Maruti',
 'Hyundai',
 'Ford',
 'Maruti',
 'Tata',
 'Maruti',
 'Honda',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Honda',
 'Toyota',
 'Hyundai',
 'Honda',
 'Hyundai',
 'Honda',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Honda',
 'Hyundai',
 'Datsun',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Tata',
 'MG',
 'Maruti',
 'Honda',
 'Hyundai',
 'Honda',
 'Hyundai',
 'MG',
 'Hyundai',
 'Tata',
 'Tata',
 'Honda',
 'Maruti',
 'Tata',
 'Hyundai',
 'Tata',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Hyundai',
 'Jeep',
 'Hyundai',
 'Hyundai',
 'Maruti',
 'Hyundai',
 'Hyundai',
 'Hyundai',
 'Ford',
 'Mahindra',
 'Tata',
 'Maruti',
 'Renault',
 'Maruti',
 'Maruti',
 'Honda',
 'Toyota',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Honda',
 'Maruti',
 'Maruti',
 'Mahindra',
 'Honda',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Tata',
 'Maruti',
 'Maruti',
 'Honda',
 'Maruti',
 'Tata',
 'Toyota',
 'Maruti',
 'Mahindra',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Honda',
 'Honda',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Honda',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Tata',
 'Hyundai',
 'Maruti',
 'Hyundai',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Honda',
 'Maruti',
 'Honda',
 'Maruti',
 'Renault',
 'Hyundai',
 'Tata',
 'Honda',
 'Renault',
 'Maruti',
 'Maruti',
 'Honda',
 'Honda',
 'Maruti',
 'Maruti',
 'Maruti',
 'Honda',
 'Renault',
 'Renault',
 'Maruti',
 'Honda',
 'Hyundai',
 'Maruti',
 'Mahindra',
 'Maruti',
 'Tata',
 'Maruti',
 'Honda',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Tata',
 'Hyundai',
 'Maruti',
 'Hyundai',
 'Hyundai',
 'Renault',
 'Hyundai',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Honda',
 'Maruti',
 'Honda',
 'Honda',
 'Maruti',
 'Maruti',
 'Maruti',
 'Volkswagen',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Honda',
 'Hyundai',
 'Volkswagen',
 'Renault',
 'Volkswagen',
 'Maruti',
 'Mahindra',
 'Maruti',
 'Hyundai',
 'Skoda',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Hyundai',
 'Honda',
 'Honda',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Honda',
 'Honda',
 'Maruti',
 'Maruti',
 'Tata',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Hyundai',
 'Tata',
 'Maruti',
 'Maruti',
 'Honda',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Honda',
 'Maruti',
 'Honda',
 'Maruti',
 'Toyota',
 'Maruti',
 'Hyundai',
 'Hyundai',
 'Renault',
 'Maruti',
 'Maruti',
 'Maruti',
 'Tata',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Renault',
 'Honda',
 'MG',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Hyundai',
 'Honda',
 'Maruti',
 'Hyundai',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Hyundai',
 'Mahindra',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Hyundai',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Hyundai',
 'Hyundai',
 'Hyundai',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Hyundai',
 'Toyota',
 'Maruti',
 'Maruti',
 'Maruti',
 'Honda',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Honda',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Toyota',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Hyundai',
 'Honda',
 'Maruti',
 'Toyota',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Honda',
 'Maruti',
 'Toyota',
 'Maruti',
 'Volkswagen',
 'Maruti',
 'Tata',
 'Honda',
 'Toyota',
 'Hyundai',
 'Honda',
 'Honda',
 'Maruti',
 'Honda',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Toyota',
 'Maruti',
 'Hyundai',
 'Hyundai',
 'Maruti',
 'Honda',
 'Hyundai',
 'Honda',
 'Maruti',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Hyundai',
 'Tata',
 'Tata',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Honda',
 'Maruti',
 'Volkswagen',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Renault',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Hyundai',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Hyundai',
 'Maruti',
 'Renault',
 'Maruti',
 'Maruti',
 'Mahindra',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Mahindra',
 'Maruti',
 'Honda',
 'Hyundai',
 'Maruti',
 'Tata',
 'Mahindra',
 'Honda',
 'Hyundai',
 'Mahindra',
 'Skoda',
 'Maruti',
 'Maruti',
 'Mahindra',
 'Hyundai',
 'Honda',
 'Hyundai',
 'Maruti',
 'Tata',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Renault',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Hyundai',
 'Mahindra',
 'Renault',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Ford',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Ford',
 'Honda',
 'Maruti',
 'Hyundai',
 'Hyundai',
 'Renault',
 'Tata',
 'Toyota',
 'Honda',
 'Maruti',
 'Maruti',
 'Maruti',
 'Volkswagen',
 'Maruti',
 'Maruti',
 'Ford',
 'Hyundai',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Maruti',
 'Honda',
 'Hyundai',
 'Maruti',
 'Toyota',
 'Toyota',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Ford',
 'Hyundai',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Hyundai',
 'Datsun',
 'Hyundai',
 'Maruti',
 'Hyundai',
 'Hyundai',
 'Maruti',
 'Hyundai',
 'Ford',
 'Maruti',
 'Nissan',
 'Honda',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Mahindra',
 'Maruti',
 'Hyundai',
 'Mahindra',
 'Maruti',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Hyundai',
 'Hyundai',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Maruti',
 'Mahindra',
 'Maruti',
 'Honda',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Hyundai',
 'Honda',
 'Mahindra',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Tata',
 'Ford',
 'Hyundai',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Hyundai',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Maruti',
 'Ford',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Hyundai',
 'Skoda',
 'Tata',
 'Hyundai',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Honda',
 'Maruti',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Hyundai',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Ford',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Volkswagen',
 'Maruti',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Mahindra',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Ford',
 'Hyundai',
 'Tata',
 'Maruti',
 'Tata',
 'Maruti',
 'Hyundai',
 'Hyundai',
 'Maruti',
 'Hyundai',
 'Toyota',
 'Maruti',
 'Maruti',
 'Maruti',
 'Mahindra',
 'Mahindra',
 'Tata',
 'Hyundai',
 'Maruti',
 'Toyota',
 'Renault',
 'Audi',
 'Hyundai',
 'Maruti',
 'Ford',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Hyundai',
 'Mahindra',
 'Maruti',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Tata',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Audi',
 'Maruti',
 'Audi',
 'Maruti',
 'Maruti',
 'Renault',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Honda',
 'Hyundai',
 'Mahindra',
 'Maruti',
 'Maruti',
 'Maruti',
 'Honda',
 'Maruti',
 'Maruti',
 'Tata',
 'Maruti',
 'Maruti',
 'Renault',
 'Maruti',
 'Maruti',
 'Toyota',
 'Maruti',
 'Maruti',
 'Maruti',
 'Hyundai',
 'Maruti',
 'Maruti',
 'Maruti',
 'Ford',
 'Maruti',
 'Hyundai',
 ...]

In [32]:
#scrapping Model
Model=[]
try:
    Model_tag=driver.find_elements(By.XPATH,'//h3[@class="_3FpCg"]')
    for j in Model_tag:
        Model.append(j.text.split(' ')[2:])
except NoSuchElementException : #handling no such element exception
    Model.append('-')

In [33]:
#Number of data scrapped
len(Model)

1080

In [34]:
#printing Model
Model

[['Swift'],
 ['SELTOS'],
 ['Swift'],
 ['SELTOS'],
 ['Grand', 'i10'],
 ['Kwid'],
 ['Grand', 'i10'],
 ['Grand', 'i10'],
 ['Swift', 'Dzire'],
 ['Swift'],
 ['SONET'],
 ['New', 'Wagon-R'],
 ['SELTOS'],
 ['Celerio'],
 ['SELTOS'],
 ['City'],
 ['NEW', 'I20'],
 ['SELTOS'],
 ['SELTOS'],
 ['Wagon', 'R', '1.0'],
 ['Wagon', 'R', '1.0'],
 ['SELTOS'],
 ['Swift'],
 ['Alto', 'K10'],
 ['KUSHAQ'],
 ['City'],
 ['SELTOS'],
 ['Celerio'],
 ['SONET'],
 ['SELTOS'],
 ['Alto'],
 ['SONET'],
 ['VENUE'],
 ['SELTOS'],
 ['Camry'],
 ['Kiger'],
 ['i10'],
 ['New', 'Wagon-R'],
 ['SELTOS'],
 ['Alto', '800'],
 ['VENUE'],
 ['SELTOS'],
 ['Kiger'],
 ['NEW', 'I20'],
 ['Kiger'],
 ['URBAN', 'CRUISER'],
 ['Grand', 'i10'],
 ['Swift', 'Dzire'],
 ['Swift'],
 ['Swift', 'Dzire'],
 ['i10'],
 ['i20'],
 ['New', 'Wagon-R'],
 ['Wagon', 'R', 'Stingray'],
 ['Safari'],
 ['SELTOS'],
 ['Kwid'],
 ['SELTOS'],
 ['Swift'],
 ['A', 'Star'],
 ['i20'],
 ['Wagon', 'R', 'Stingray'],
 ['Grand', 'i10'],
 ['SELTOS'],
 ['A', 'Star'],
 ['City'],
 ['Kwid'],
 ['Grand', 'i10'],
 ['Eon'],
 ['Kwid'],
 ['Kiger'],
 ['Kwid'],
 ['AURA'],
 ['AURA'],
 ['Kwid'],
 ['i10'],
 ['Kiger'],
 ['Celerio'],
 ['Go', 'Plus'],
 ['New', 'Wagon-R'],
 ['Kwid'],
 ['Redi', 'Go'],
 ['Redi', 'Go'],
 ['Ecosport'],
 ['AURA'],
 ['URBAN', 'CRUISER'],
 ['Wagon', 'R', '1.0'],
 ['Swift'],
 ['New', 'Wagon-R'],
 ['City'],
 ['City'],
 ['A', 'Star'],
 ['Rapid'],
 ['New', 'Wagon-R'],
 ['Wagon', 'R', '1.0'],
 ['URBAN', 'CRUISER'],
 ['Kiger'],
 ['Wagon', 'R', 'Stingray'],
 ['Baleno'],
 ['Wagon', 'R', '1.0'],
 ['Grand', 'i10'],
 ['MAGNITE'],
 ['Alto', 'K10'],
 ['Grand', 'i10'],
 ['Elite', 'i20'],
 ['i10'],
 ['Kiger'],
 ['City'],
 ['AURA'],
 ['Kiger'],
 ['Verna'],
 ['Compass'],
 ['Kiger'],
 ['ALTROZ'],
 ['Verna'],
 ['Kwid'],
 ['Thar'],
 ['Alto', '800'],
 ['Ritz'],
 ['Baleno'],
 ['City'],
 ['New', 'Wagon-R'],
 ['Safari'],
 ['Swift'],
 ['Alto', 'K10'],
 ['City'],
 ['SONET'],
 ['i20'],
 ['ALTROZ'],
 ['Tiago'],
 ['City'],
 ['Alto', 'K10'],
 ['New', 'Wagon-R'],
 ['City'],
 ['Ciaz'],
 ['Alto'],
 ['Ecosport'],
 ['New', 'Wagon-R'],
 ['Elite', 'i20'],
 ['New', 'Wagon-R'],
 ['Alto', '800'],
 ['i20'],
 ['City'],
 ['Swift', 'Dzire'],
 ['Wagon', 'R', '1.0'],
 ['Celerio'],
 ['Grand', 'i10'],
 ['BREZZA'],
 ['Tiago'],
 ['Wagon', 'R', '1.0'],
 ['Kwid'],
 ['City'],
 ['New', 'Wagon-R'],
 ['ALTROZ'],
 ['New', 'Wagon-R'],
 ['Swift'],
 ['i10'],
 ['City'],
 ['City'],
 ['New', 'Wagon-R'],
 ['City'],
 ['City'],
 ['S', 'Cross'],
 ['Baleno'],
 ['Amaze'],
 ['Alto', 'K10'],
 ['Alto'],
 ['i20'],
 ['New', 'Wagon-R'],
 ['City'],
 ['Verna'],
 ['City'],
 ['Amaze'],
 ['Amaze'],
 ['Baleno'],
 ['Amaze'],
 ['Glanza'],
 ['Swift'],
 ['Baleno'],
 ['City'],
 ['Alto', '800'],
 ['Thar'],
 ['New', 'Wagon-R'],
 ['Grand', 'i10'],
 ['YARIS'],
 ['ALTROZ'],
 ['Verna'],
 ['Alto', 'K10'],
 ['Thar'],
 ['Amaze'],
 ['ALTROZ'],
 ['City'],
 ['Amaze'],
 ['Grand', 'i10'],
 ['Compass'],
 ['Innova', 'Crysta'],
 ['Grand', 'i10'],
 ['Elite', 'i20'],
 ['ALTROZ'],
 ['Swift'],
 ['Alto', 'K10'],
 ['City'],
 ['Verna'],
 ['Alto'],
 ['KUV', '100', 'NXT'],
 ['Celerio'],
 ['City'],
 ['Baleno'],
 ['Brio'],
 ['Dzire'],
 ['ALTROZ'],
 ['City'],
 ['City'],
 ['City'],
 ['Verna'],
 ['NEXON'],
 ['City'],
 ['Swift'],
 ['Elite', 'i20'],
 ['New', 'Wagon-R'],
 ['City'],
 ['Harrier'],
 ['Amaze'],
 ['Verna'],
 ['Alto', '800'],
 ['Amaze'],
 ['Grand', 'i10'],
 ['New', 'Wagon-R'],
 ['ALTROZ'],
 ['Alto', 'K10'],
 ['Wagon', 'R', '1.0'],
 ['i10'],
 ['ALTROZ'],
 ['NEW', 'SANTRO'],
 ['Kwid'],
 ['Rapid'],
 ['City'],
 ['ALTROZ'],
 ['Swift', 'Dzire'],
 ['City'],
 ['VENUE'],
 ['City'],
 ['Baleno'],
 ['Wagon', 'R', '1.0'],
 ['ALTROZ'],
 ['City'],
 ['Swift'],
 ['Amaze'],
 ['Swift'],
 ['ALTROZ'],
 ['Grand', 'i10'],
 ['New', 'Wagon-R'],
 ['Amaze'],
 ['Verna'],
 ['Kwid'],
 ['City'],
 ['Octavia'],
 ['Verna'],
 ['City'],
 ['Redi', 'Go'],
 ['TRIBER'],
 ['New', 'Wagon-R'],
 ['Brio'],
 ['Swift'],
 ['Baleno'],
 ['Ciaz'],
 ['Swift'],
 ['Amaze'],
 ['Elite', 'i20'],
 ['Grand', 'i10'],
 ['i20'],
 ['Elite', 'i20'],
 ['Kwid'],
 ['Grand', 'i10'],
 ['Grand', 'i10'],
 ['Jazz'],
 ['Dzire'],
 ['Alto', '800'],
 ['Elite', 'i20'],
 ['New', 'Wagon-R'],
 ['New', 'Wagon-R'],
 ['Ecosport'],
 ['Kwid'],
 ['Duster'],
 ['Grand', 'i10'],
 ['Swift'],
 ['City'],
 ['City'],
 ['Amaze'],
 ['Amaze'],
 ['New', 'Wagon-R'],
 ['Baleno'],
 ['Celerio'],
 ['Wagon', 'R', '1.0'],
 ['Elite', 'i20'],
 ['YARIS'],
 ['City'],
 ['NEW', 'SANTRO'],
 ['Swift'],
 ['Glanza'],
 ['Swift'],
 ['Grand', 'i10'],
 ['Figo', 'Aspire'],
 ['New', 'Wagon-R'],
 ['Tiago'],
 ['New', 'Wagon-R'],
 ['City'],
 ['Xcent'],
 ['Ertiga'],
 ['Baleno'],
 ['Jazz'],
 ['Corolla', 'Altis'],
 ['Grand', 'i10'],
 ['City'],
 ['i10'],
 ['Jazz'],
 ['Dzire'],
 ['Alto', 'K10'],
 ['New', 'Wagon-R'],
 ['Celerio'],
 ['New', 'Wagon-R'],
 ['Amaze'],
 ['i10'],
 ['Redi', 'Go'],
 ['Baleno'],
 ['Swift'],
 ['Celerio'],
 ['Ciaz'],
 ['A', 'Star'],
 ['Ritz'],
 ['Tiago'],
 ['HECTOR'],
 ['Celerio'],
 ['City'],
 ['Xcent'],
 ['City'],
 ['Creta'],
 ['HECTOR'],
 ['Creta'],
 ['Tiago'],
 ['Safari'],
 ['City'],
 ['Swift'],
 ['NEXON'],
 ['Eon'],
 ['Harrier'],
 ['Wagon', 'R', '1.0'],
 ['Alto'],
 ['Verna'],
 ['Celerio'],
 ['Wagon', 'R', '1.0'],
 ['Xcent'],
 ['Grand', 'i10'],
 ['Compass'],
 ['Verna'],
 ['Grand', 'i10'],
 ['Alto'],
 ['Grand', 'i10'],
 ['Grand', 'i10'],
 ['Elite', 'i20'],
 ['Ecosport'],
 ['Thar'],
 ['Tiago'],
 ['New', 'Wagon-R'],
 ['Kwid'],
 ['Baleno'],
 ['New', 'Wagon-R'],
 ['Amaze'],
 ['Corolla', 'Altis'],
 ['Grand', 'i10'],
 ['Alto', 'K10'],
 ['S', 'Cross'],
 ['Swift'],
 ['New', 'Wagon-R'],
 ['Alto', 'K10'],
 ['WR-V'],
 ['Alto'],
 ['Alto', 'K10'],
 ['XUV500'],
 ['City'],
 ['New', 'Wagon-R'],
 ['New', 'Wagon-R'],
 ['Elite', 'i20'],
 ['Dzire'],
 ['Dzire'],
 ['Elite', 'i20'],
 ['Ciaz'],
 ['Grand', 'i10'],
 ['IGNIS'],
 ['New', 'Wagon-R'],
 ['ALTROZ'],
 ['Dzire'],
 ['New', 'Wagon-R'],
 ['Brio'],
 ['S', 'PRESSO'],
 ['ALTROZ'],
 ['Glanza'],
 ['S', 'Cross'],
 ['XUV500'],
 ['Xcent'],
 ['Baleno'],
 ['Ciaz'],
 ['Swift'],
 ['Elite', 'i20'],
 ['Amaze'],
 ['Jazz'],
 ['Elite', 'i20'],
 ['Wagon', 'R', '1.0'],
 ['New', 'Wagon-R'],
 ['Alto'],
 ['IGNIS'],
 ['New', 'Wagon-R'],
 ['Alto'],
 ['City'],
 ['Swift'],
 ['Baleno'],
 ['NEW', 'SANTRO'],
 ['Baleno'],
 ['NEXON'],
 ['Grand', 'i10'],
 ['XL6'],
 ['Grand', 'i10'],
 ['NEW', 'SANTRO'],
 ['New', 'Wagon-R'],
 ['Celerio'],
 ['Amaze'],
 ['Alto', 'K10'],
 ['City'],
 ['Alto', 'K10'],
 ['Kwid'],
 ['Grand', 'i10'],
 ['Tiago'],
 ['Amaze'],
 ['Kwid'],
 ['Alto', '800'],
 ['Wagon', 'R', '1.0'],
 ['Jazz'],
 ['WR-V'],
 ['New', 'Wagon-R'],
 ['Baleno'],
 ['Baleno'],
 ['Amaze'],
 ['TRIBER'],
 ['Kwid'],
 ['Baleno'],
 ['Amaze'],
 ['Elite', 'i20'],
 ['New', 'Wagon-R'],
 ['XUV500'],
 ['New', 'Wagon-R'],
 ['ALTROZ'],
 ['New', 'Wagon-R'],
 ['Brio'],
 ['Baleno'],
 ['Baleno'],
 ['Alto', 'K10'],
 ['Baleno'],
 ['Baleno'],
 ['New', 'Wagon-R'],
 ['A', 'Star'],
 ['Swift'],
 ['Baleno'],
 ['NEXON'],
 ['VENUE'],
 ['New', 'Wagon-R'],
 ['Elite', 'i20'],
 ['Grand', 'i10'],
 ['Kwid'],
 ['Grand', 'i10'],
 ['VENUE'],
 ['Celerio', 'X'],
 ['Swift'],
 ['New', 'Wagon-R'],
 ['Creta'],
 ['Swift'],
 ['Wagon', 'R', '1.0'],
 ['New', 'Wagon-R'],
 ['New', 'Wagon-R'],
 ['Alto'],
 ['Amaze'],
 ['Baleno'],
 ['City'],
 ['Jazz'],
 ['Ciaz'],
 ['Swift'],
 ['Wagon', 'R', '1.0'],
 ['Polo'],
 ['New', 'Wagon-R'],
 ['S', 'PRESSO'],
 ['S', 'PRESSO'],
 ['S', 'PRESSO'],
 ['S', 'PRESSO'],
 ['S', 'PRESSO'],
 ['S', 'PRESSO'],
 ['S', 'PRESSO'],
 ['S', 'PRESSO'],
 ['Alto'],
 ['Elite', 'i20'],
 ['City'],
 ['Grand', 'i10'],
 ['Vento'],
 ['Kwid'],
 ['Vento'],
 ['New', 'Wagon-R'],
 ['MARAZZO'],
 ['Vitara', 'Brezza'],
 ['Grand', 'i10'],
 ['Rapid'],
 ['New', 'Wagon-R'],
 ['Alto'],
 ['New', 'Wagon-R'],
 ['Swift'],
 ['Swift'],
 ['New', 'Wagon-R'],
 ['Celerio'],
 ['New', 'Wagon-R'],
 ['Creta'],
 ['Grand', 'i10'],
 ['Jazz'],
 ['Jazz'],
 ['Swift'],
 ['Grand', 'i10'],
 ['Alto'],
 ['Baleno'],
 ['Elite', 'i20'],
 ['Jazz'],
 ['Jazz'],
 ['Baleno'],
 ['Swift'],
 ['Harrier'],
 ['Elite', 'i20'],
 ['Alto', '800'],
 ['Celerio', 'X'],
 ['Ciaz'],
 ['Baleno'],
 ['Grand', 'i10'],
 ['NEW', 'SANTRO'],
 ['Harrier'],
 ['Ciaz'],
 ['Baleno'],
 ['Jazz'],
 ['Ciaz'],
 ['Baleno'],
 ['VENUE'],
 ['Amaze'],
 ['New', 'Wagon-R'],
 ['City'],
 ['Baleno'],
 ['Innova', 'Crysta'],
 ['S', 'PRESSO'],
 ['Grand', 'i10'],
 ['GRAND', 'I10', 'NIOS'],
 ['Kwid'],
 ['Baleno'],
 ['Baleno'],
 ['Ciaz'],
 ['Tiago'],
 ['Ciaz'],
 ['New', 'Wagon-R'],
 ['Elite', 'i20'],
 ['Celerio'],
 ['Swift'],
 ['New', 'Wagon-R'],
 ['Baleno'],
 ['New', 'Wagon-R'],
 ['Duster'],
 ['Brio'],
 ['HECTOR'],
 ['New', 'Wagon-R'],
 ['Swift'],
 ['Grand', 'i10'],
 ['Baleno'],
 ['NEW', 'SANTRO'],
 ['New', 'Wagon-R'],
 ['Grand', 'i10'],
 ['Ciaz'],
 ['NEW', 'SANTRO'],
 ['Jazz'],
 ['Alto'],
 ['Creta'],
 ['Elite', 'i20'],
 ['Baleno'],
 ['Baleno'],
 ['Alto'],
 ['Swift'],
 ['Creta'],
 ['Creta'],
 ['Scorpio'],
 ['Baleno'],
 ['Baleno'],
 ['Creta'],
 ['Elite', 'i20'],
 ['Grand', 'i10'],
 ['Baleno'],
 ['Baleno'],
 ['Swift'],
 ['Grand', 'i10'],
 ['Baleno'],
 ['Elite', 'i20'],
 ['Grand', 'i10'],
 ['Elite', 'i20'],
 ['Baleno'],
 ['GRAND', 'I10', 'NIOS'],
 ['Baleno'],
 ['i10'],
 ['Corolla', 'Altis'],
 ['Alto'],
 ['S', 'Cross'],
 ['Celerio'],
 ['City'],
 ['GRAND', 'I10', 'NIOS'],
 ['Alto', '800'],
 ['Baleno'],
 ['City'],
 ['Baleno'],
 ['Celerio'],
 ['Creta'],
 ['Baleno'],
 ['Ciaz'],
 ['Celerio'],
 ['Creta'],
 ['Corolla', 'Altis'],
 ['Alto', '800'],
 ['Alto'],
 ['New', 'Wagon-R'],
 ['Wagon', 'R', '1.0'],
 ['Grand', 'i10'],
 ['Elite', 'i20'],
 ['Jazz'],
 ['Baleno'],
 ['Etios'],
 ['Grand', 'i10'],
 ['Alto', 'K10'],
 ['IGNIS'],
 ['GRAND', 'I10', 'NIOS'],
 ['Swift'],
 ['Amaze'],
 ['Ciaz'],
 ['Corolla', 'Altis'],
 ['Baleno'],
 ['Polo'],
 ['Swift'],
 ['NEXON'],
 ['Brio'],
 ['Corolla', 'Altis'],
 ['NEW', 'SANTRO'],
 ['Brio'],
 ['WR-V'],
 ['Ertiga'],
 ['Amaze'],
 ['Grand', 'i10'],
 ['New', 'Wagon-R'],
 ['New', 'Wagon-R'],
 ['YARIS'],
 ['S', 'PRESSO'],
 ['Grand', 'i10'],
 ['Grand', 'i10'],
 ['New', 'Wagon-R'],
 ['Amaze'],
 ['Grand', 'i10'],
 ['Jazz'],
 ['Alto', 'K10'],
 ['New', 'Wagon-R'],
 ['Baleno'],
 ['Grand', 'i10'],
 ['Verna'],
 ['Tiago'],
 ['NEXON'],
 ['Vitara', 'Brezza'],
 ['Creta'],
 ['Baleno'],
 ['City'],
 ['Wagon', 'R', '1.0'],
 ['Polo'],
 ['Baleno'],
 ['New', 'Wagon-R'],
 ['Grand', 'i10'],
 ['Alto'],
 ['Grand', 'i10'],
 ['New', 'Wagon-R'],
 ['Kwid'],
 ['Baleno'],
 ['Elite', 'i20'],
 ['Ciaz'],
 ['Creta'],
 ['Grand', 'i10'],
 ['Baleno'],
 ['New', 'Wagon-R'],
 ['New', 'Wagon-R'],
 ['Alto'],
 ['Grand', 'i10'],
 ['Grand', 'i10'],
 ['Swift'],
 ['TRIBER'],
 ['Baleno'],
 ['Baleno'],
 ['Thar'],
 ['Ciaz'],
 ['S', 'Cross'],
 ['Grand', 'i10'],
 ['Alto'],
 ['Baleno'],
 ['XUV', '3OO'],
 ['Ciaz'],
 ['WR-V'],
 ['VENUE'],
 ['Baleno'],
 ['NEXON'],
 ['XUV500'],
 ['Brio'],
 ['NEW', 'SANTRO'],
 ['Scorpio'],
 ['Rapid'],
 ['Dzire'],
 ['Ciaz'],
 ['Thar'],
 ['Xcent'],
 ['WR-V'],
 ['Creta'],
 ['Swift'],
 ['Tiago'],
 ['Alto'],
 ['Baleno'],
 ['Grand', 'i10'],
 ['Alto', 'K10'],
 ['Kwid'],
 ['VENUE'],
 ['IGNIS'],
 ['Swift'],
 ['Wagon', 'R', '1.0'],
 ['Ciaz'],
 ['NEW', 'SANTRO'],
 ['Elite', 'i20'],
 ['Scorpio'],
 ['Kwid'],
 ['New', 'Wagon-R'],
 ['Celerio'],
 ['Elite', 'i20'],
 ['New', 'Wagon-R'],
 ['Ecosport'],
 ['Wagon', 'R', '1.0'],
 ['Vitara', 'Brezza'],
 ['Baleno'],
 ['Alto', 'K10'],
 ['Swift'],
 ['Ecosport'],
 ['WR-V'],
 ['New', 'Wagon-R'],
 ['Grand', 'i10'],
 ['GRAND', 'I10', 'NIOS'],
 ['Kwid'],
 ['Tiago'],
 ['Corolla', 'Altis'],
 ['WR-V'],
 ['New', 'Wagon-R'],
 ['New', 'Wagon-R'],
 ['Swift'],
 ['Vento'],
 ['S', 'PRESSO'],
 ['Wagon', 'R', '1.0'],
 ['Ecosport'],
 ['Tucson', 'New'],
 ['Elite', 'i20'],
 ['Alto', 'K10'],
 ['Baleno'],
 ['Swift'],
 ['Brio'],
 ['Elite', 'i20'],
 ['Baleno'],
 ['YARIS'],
 ['Etios'],
 ['Swift'],
 ['New', 'Wagon-R'],
 ['GRAND', 'I10', 'NIOS'],
 ['Ecosport'],
 ['Elite', 'i20'],
 ['NEW', 'SANTRO'],
 ['Alto', 'K10'],
 ['Alto', 'K10'],
 ['Grand', 'i10'],
 ['Swift'],
 ['Grand', 'i10'],
 ['S', 'PRESSO'],
 ['New', 'Wagon-R'],
 ['Xcent'],
 ['Creta'],
 ['Redi', 'Go'],
 ['GRAND', 'I10', 'NIOS'],
 ['Baleno'],
 ['GRAND', 'I10', 'NIOS'],
 ['NEW', 'SANTRO'],
 ['Swift'],
 ['GRAND', 'I10', 'NIOS'],
 ['FREESTYLE'],
 ['Alto', 'K10'],
 ['Micra', 'Active'],
 ['Jazz'],
 ['Baleno'],
 ['Ciaz'],
 ['Baleno'],
 ['Ciaz'],
 ['Baleno'],
 ['Bolero'],
 ['Baleno'],
 ['Creta'],
 ['TUV300'],
 ['Baleno'],
 ['XL6'],
 ['Ciaz'],
 ['Xcent'],
 ['NEW', 'SANTRO'],
 ['Elite', 'i20'],
 ['GRAND', 'I10', 'NIOS'],
 ['New', 'Wagon-R'],
 ['Baleno'],
 ['Baleno'],
 ['Scorpio'],
 ['Wagon', 'R', '1.0'],
 ['Jazz'],
 ['Grand', 'i10'],
 ['Vitara', 'Brezza'],
 ['Baleno'],
 ['IGNIS'],
 ['Elite', 'i20'],
 ['Celerio'],
 ['New', 'Elantra'],
 ['Brio'],
 ['Thar'],
 ['Creta'],
 ['Baleno'],
 ['Celerio'],
 ['NEW', 'SANTRO'],
 ['ALTROZ'],
 ['FREESTYLE'],
 ['Creta'],
 ['Celerio'],
 ['Creta'],
 ['Ciaz'],
 ['Creta'],
 ['Grand', 'i10'],
 ['Baleno'],
 ['S', 'PRESSO'],
 ['Creta'],
 ['S', 'PRESSO'],
 ['S', 'Cross'],
 ['Baleno'],
 ['Ecosport'],
 ['Baleno'],
 ['Creta'],
 ['Celerio'],
 ['NEW', 'SANTRO'],
 ['Rapid'],
 ['Tiago'],
 ['NEW', 'SANTRO'],
 ['VENUE'],
 ['Alto', 'K10'],
 ['Swift'],
 ['Dzire'],
 ['Baleno'],
 ['i20', 'Active'],
 ['Swift'],
 ['Baleno'],
 ['Creta'],
 ['Amaze'],
 ['Celerio'],
 ['Vitara', 'Brezza'],
 ['Vitara', 'Brezza'],
 ['Elite', 'i20'],
 ['Creta'],
 ['Baleno'],
 ['Elite', 'i20'],
 ['Celerio'],
 ['Creta'],
 ['Swift'],
 ['Baleno'],
 ['Creta'],
 ['Baleno'],
 ['Wagon', 'R', '1.0'],
 ['NEW', 'SANTRO'],
 ['Ciaz'],
 ['Baleno'],
 ['i20'],
 ['Swift'],
 ['Grand', 'i10'],
 ['Celerio'],
 ['Grand', 'i10'],
 ['New', 'Wagon-R'],
 ['GRAND', 'I10', 'NIOS'],
 ['S', 'Cross'],
 ['IGNIS'],
 ['Vitara', 'Brezza'],
 ['Baleno'],
 ['Baleno'],
 ['Ecosport'],
 ['Swift'],
 ['Ciaz'],
 ['S', 'PRESSO'],
 ['Alto'],
 ['Baleno'],
 ['TIGUAN'],
 ['Baleno'],
 ['Vitara', 'Brezza'],
 ['Baleno'],
 ['Grand', 'i10'],
 ['Vitara', 'Brezza'],
 ['Swift'],
 ['Swift'],
 ['Vitara', 'Brezza'],
 ['Scorpio'],
 ['Creta'],
 ['Baleno'],
 ['Alto', 'K10'],
 ['GRAND', 'I10', 'NIOS'],
 ['Creta'],
 ['S', 'PRESSO'],
 ['Alto'],
 ['Ecosport'],
 ['Grand', 'i10'],
 ['NEXON'],
 ['Vitara', 'Brezza'],
 ['Hexa'],
 ['IGNIS'],
 ['Creta'],
 ['Elite', 'i20'],
 ['Baleno'],
 ['Grand', 'i10'],
 ['Etios'],
 ['Ciaz'],
 ['S', 'PRESSO'],
 ['New', 'Wagon-R'],
 ['XUV', '3OO'],
 ['XUV', '3OO'],
 ['Hexa'],
 ['VENUE'],
 ['Vitara', 'Brezza'],
 ['Corolla', 'Altis'],
 ['Duster'],
 ['A3'],
 ['Creta'],
 ['Vitara', 'Brezza'],
 ['Ecosport'],
 ['Vitara', 'Brezza'],
 ['Ciaz'],
 ['Baleno'],
 ['IGNIS'],
 ['Alto', 'K10'],
 ['Elite', 'i20'],
 ['Baleno'],
 ['NEW', 'SANTRO'],
 ['XUV', '3OO'],
 ['Vitara', 'Brezza'],
 ['Baleno'],
 ['Baleno'],
 ['Grand', 'i10'],
 ['Hexa'],
 ['Creta'],
 ['Vitara', 'Brezza'],
 ['Alto'],
 ['Q3'],
 ['IGNIS'],
 ['Q5'],
 ['Swift'],
 ['Baleno'],
 ['Duster'],
 ['Vitara', 'Brezza'],
 ['Baleno'],
 ['Vitara', 'Brezza'],
 ['Vitara', 'Brezza'],
 ['Vitara', 'Brezza'],
 ['Vitara', 'Brezza'],
 ['Alto'],
 ['IGNIS'],
 ['Vitara', 'Brezza'],
 ['Creta'],
 ['City'],
 ['Creta'],
 ['TUV300'],
 ['Ciaz'],
 ['Vitara', 'Brezza'],
 ['Vitara', 'Brezza'],
 ['BR-V'],
 ['Vitara', 'Brezza'],
 ['Vitara', 'Brezza'],
 ['Tiago'],
 ['Vitara', 'Brezza'],
 ['Vitara', 'Brezza'],
 ['Duster'],
 ['Vitara', 'Brezza'],
 ['IGNIS'],
 ['Innova', 'Crysta'],
 ['Celerio'],
 ['S', 'Cross'],
 ['Vitara', 'Brezza'],
 ['i20', 'Active'],
 ['Vitara', 'Brezza'],
 ['Vitara', 'Brezza'],
 ['Vitara', 'Brezza'],
 ['Ecosport'],
 ['Vitara', 'Brezza'],
 ['Creta'],
 ...]

In [35]:
#scrapping Year
Year=[]
try:
    Year_tag=driver.find_elements(By.XPATH,'//h3[@class="_3FpCg"]')
    for j in Year_tag:
        Year.append(j.text.split(' ')[0])
except NoSuchElementException : #handling no such element exception
    Year.append('-')

In [36]:
#Number of data scrapped
len(Year)

1080

In [37]:
#printing Year
Year

['2020',
 '2020',
 '2020',
 '2020',
 '2019',
 '2016',
 '2019',
 '2019',
 '2009',
 '2021',
 '2020',
 '2022',
 '2020',
 '2021',
 '2020',
 '2010',
 '2021',
 '2019',
 '2019',
 '2011',
 '2014',
 '2020',
 '2020',
 '2011',
 '2022',
 '2012',
 '2019',
 '2015',
 '2021',
 '2019',
 '2010',
 '2020',
 '2021',
 '2020',
 '2015',
 '2021',
 '2012',
 '2021',
 '2019',
 '2013',
 '2021',
 '2021',
 '2022',
 '2021',
 '2021',
 '2020',
 '2014',
 '2012',
 '2019',
 '2012',
 '2013',
 '2013',
 '2020',
 '2013',
 '2021',
 '2020',
 '2021',
 '2020',
 '2021',
 '2012',
 '2014',
 '2013',
 '2014',
 '2019',
 '2012',
 '2014',
 '2020',
 '2018',
 '2014',
 '2019',
 '2021',
 '2021',
 '2020',
 '2021',
 '2022',
 '2011',
 '2022',
 '2017',
 '2020',
 '2021',
 '2022',
 '2018',
 '2021',
 '2015',
 '2021',
 '2021',
 '2011',
 '2010',
 '2019',
 '2013',
 '2018',
 '2009',
 '2020',
 '2020',
 '2015',
 '2021',
 '2021',
 '2013',
 '2016',
 '2017',
 '2020',
 '2021',
 '2012',
 '2014',
 '2015',
 '2013',
 '2021',
 '2012',
 '2021',
 '2022',
 '2017',
 '2019',
 '2021',
 '2020',
 '2013',
 '2019',
 '2021',
 '2016',
 '2012',
 '2018',
 '2017',
 '2022',
 '2022',
 '2012',
 '2014',
 '2017',
 '2021',
 '2013',
 '2020',
 '2021',
 '2014',
 '2017',
 '2021',
 '2016',
 '2018',
 '2021',
 '2015',
 '2020',
 '2015',
 '2021',
 '2018',
 '2013',
 '2021',
 '2016',
 '2018',
 '2019',
 '2014',
 '2022',
 '2021',
 '2013',
 '2019',
 '2017',
 '2019',
 '2021',
 '2020',
 '2019',
 '2014',
 '2017',
 '2018',
 '2022',
 '2017',
 '2022',
 '2022',
 '2020',
 '2019',
 '2011',
 '2020',
 '2014',
 '2021',
 '2013',
 '2013',
 '2017',
 '2018',
 '2015',
 '2019',
 '2015',
 '2020',
 '2015',
 '2020',
 '2017',
 '2018',
 '2021',
 '2021',
 '2018',
 '2021',
 '2020',
 '2018',
 '2018',
 '2021',
 '2014',
 '2021',
 '2019',
 '2019',
 '2015',
 '2019',
 '2021',
 '2015',
 '2019',
 '2020',
 '2019',
 '2010',
 '2018',
 '2019',
 '2021',
 '2020',
 '2022',
 '2012',
 '2019',
 '2012',
 '2018',
 '2020',
 '2020',
 '2020',
 '2014',
 '2019',
 '2021',
 '2015',
 '2013',
 '2016',
 '2021',
 '2017',
 '2022',
 '2014',
 '2017',
 '2018',
 '2020',
 '2015',
 '2020',
 '2020',
 '2019',
 '2011',
 '2011',
 '2020',
 '2021',
 '2019',
 '2020',
 '2015',
 '2020',
 '2014',
 '2020',
 '2020',
 '2014',
 '2019',
 '2014',
 '2020',
 '2014',
 '2019',
 '2019',
 '2013',
 '2020',
 '2014',
 '2021',
 '2019',
 '2016',
 '2021',
 '2017',
 '2014',
 '2017',
 '2014',
 '2021',
 '2020',
 '2021',
 '2014',
 '2019',
 '2020',
 '2021',
 '2019',
 '2018',
 '2017',
 '2017',
 '2014',
 '2019',
 '2019',
 '2017',
 '2017',
 '2019',
 '2017',
 '2018',
 '2016',
 '2021',
 '2021',
 '2015',
 '2018',
 '2021',
 '2018',
 '2019',
 '2017',
 '2016',
 '2019',
 '2018',
 '2021',
 '2019',
 '2015',
 '2017',
 '2017',
 '2018',
 '2018',
 '2019',
 '2019',
 '2021',
 '2019',
 '2017',
 '2019',
 '2021',
 '2022',
 '2019',
 '2020',
 '2015',
 '2013',
 '2019',
 '2017',
 '2010',
 '2013',
 '2020',
 '2015',
 '2015',
 '2017',
 '2017',
 '2019',
 '2017',
 '2020',
 '2015',
 '2014',
 '2018',
 '2019',
 '2019',
 '2016',
 '2019',
 '2012',
 '2013',
 '2022',
 '2019',
 '2019',
 '2017',
 '2014',
 '2021',
 '2016',
 '2019',
 '2018',
 '2017',
 '2021',
 '2017',
 '2013',
 '2019',
 '2018',
 '2022',
 '2014',
 '2020',
 '2013',
 '2015',
 '2017',
 '2019',
 '2018',
 '2017',
 '2018',
 '2017',
 '2021',
 '2015',
 '2015',
 '2016',
 '2016',
 '2021',
 '2019',
 '2020',
 '2020',
 '2020',
 '2019',
 '2019',
 '2015',
 '2015',
 '2016',
 '2021',
 '2015',
 '2020',
 '2018',
 '2017',
 '2021',
 '2011',
 '2019',
 '2017',
 '2020',
 '2020',
 '2016',
 '2018',
 '2017',
 '2015',
 '2018',
 '2018',
 '2018',
 '2020',
 '2021',
 '2017',
 '2020',
 '2012',
 '2021',
 '2021',
 '2021',
 '2021',
 '2019',
 '2018',
 '2020',
 '2020',
 '2012',
 '2019',
 '2019',
 '2016',
 '2019',
 '2014',
 '2021',
 '2021',
 '2020',
 '2019',
 '2021',
 '2014',
 '2018',
 '2022',
 '2021',
 '2016',
 '2021',
 '2015',
 '2019',
 '2018',
 '2020',
 '2021',
 '2016',
 '2021',
 '2017',
 '2020',
 '2017',
 '2020',
 '2017',
 '2019',
 '2014',
 '2019',
 '2018',
 '2018',
 '2016',
 '2021',
 '2021',
 '2019',
 '2020',
 '2016',
 '2020',
 '2017',
 '2021',
 '2017',
 '2016',
 '2020',
 '2019',
 '2021',
 '2021',
 '2020',
 '2013',
 '2016',
 '2016',
 '2018',
 '2015',
 '2019',
 '2019',
 '2012',
 '2013',
 '2019',
 '2020',
 '2021',
 '2019',
 '2019',
 '2014',
 '2020',
 '2015',
 '2019',
 '2019',
 '2019',
 '2020',
 '2019',
 '2021',
 '2018',
 '2021',
 '2021',
 '2019',
 '2018',
 '2017',
 '2017',
 '2016',
 '2019',
 '2018',
 '2018',
 '2020',
 '2020',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2020',
 '2019',
 '2017',
 '2016',
 '2014',
 '2020',
 '2020',
 '2021',
 '2019',
 '2020',
 '2016',
 '2021',
 '2021',
 '2021',
 '2019',
 '2013',
 '2016',
 '2020',
 '2018',
 '2020',
 '2020',
 '2015',
 '2020',
 '2017',
 '2019',
 '2018',
 '2021',
 '2022',
 '2015',
 '2017',
 '2017',
 '2016',
 '2021',
 '2021',
 '2015',
 '2018',
 '2018',
 '2014',
 '2016',
 '2017',
 '2020',
 '2019',
 '2019',
 '2017',
 '2015',
 '2019',
 '2020',
 '2019',
 '2019',
 '2022',
 '2018',
 '2016',
 '2019',
 '2021',
 '2018',
 '2019',
 '2020',
 '2017',
 '2016',
 '2019',
 '2020',
 '2017',
 '2020',
 '2019',
 '2017',
 '2014',
 '2021',
 '2019',
 '2019',
 '2021',
 '2013',
 '2019',
 '2020',
 '2013',
 '2017',
 '2018',
 '2021',
 '2021',
 '2016',
 '2019',
 '2020',
 '2015',
 '2021',
 '2016',
 '2016',
 '2019',
 '2020',
 '2021',
 '2018',
 '2018',
 '2015',
 '2020',
 '2016',
 '2017',
 '2016',
 '2017',
 '2014',
 '2020',
 '2017',
 '2012',
 '2019',
 '2020',
 '2016',
 '2018',
 '2018',
 '2019',
 '2020',
 '2020',
 '2011',
 '2017',
 '2021',
 '2021',
 '2016',
 '2018',
 '2021',
 '2018',
 '2018',
 '2018',
 '2020',
 '2019',
 '2018',
 '2018',
 '2018',
 '2021',
 '2020',
 '2017',
 '2018',
 '2021',
 '2019',
 '2018',
 '2016',
 '2017',
 '2016',
 '2017',
 '2011',
 '2017',
 '2018',
 '2021',
 '2021',
 '2016',
 '2016',
 '2016',
 '2017',
 '2016',
 '2021',
 '2014',
 '2021',
 '2013',
 '2015',
 '2019',
 '2015',
 '2019',
 '2014',
 '2018',
 '2018',
 '2019',
 '2020',
 '2020',
 '2021',
 '2017',
 '2016',
 '2019',
 '2016',
 '2016',
 '2017',
 '2018',
 '2020',
 '2016',
 '2017',
 '2016',
 '2020',
 '2021',
 '2020',
 '2019',
 '2020',
 '2018',
 '2018',
 '2017',
 '2016',
 '2020',
 '2018',
 '2019',
 '2015',
 '2019',
 '2019',
 '2020',
 '2017',
 '2018',
 '2018',
 '2016',
 '2017',
 '2019',
 '2020',
 '2021',
 '2015',
 '2016',
 '2018',
 '2020',
 '2019',
 '2016',
 '2022',
 '2021',
 '2020',
 '2016',
 '2021',
 '2016',
 '2021',
 '2017',
 '2018',
 '2019',
 '2019',
 '2018',
 '2018',
 '2016',
 '2019',
 '2019',
 '2020',
 '2020',
 '2018',
 '2019',
 '2015',
 '2017',
 '2019',
 '2014',
 '2022',
 '2021',
 '2016',
 '2016',
 '2018',
 '2019',
 '2020',
 '2018',
 '2015',
 '2018',
 '2018',
 '2019',
 '2015',
 '2021',
 '2019',
 '2019',
 '2020',
 '2017',
 '2019',
 '2018',
 '2017',
 '2020',
 '2019',
 '2019',
 '2018',
 '2017',
 '2020',
 '2019',
 '2016',
 '2020',
 '2018',
 '2019',
 '2016',
 '2018',
 '2019',
 '2019',
 '2015',
 '2019',
 '2021',
 '2018',
 '2016',
 '2018',
 '2017',
 '2015',
 '2020',
 '2014',
 '2015',
 '2019',
 '2018',
 '2020',
 '2017',
 '2019',
 '2019',
 '2021',
 '2017',
 '2019',
 '2019',
 '2019',
 '2018',
 '2015',
 '2018',
 '2014',
 '2021',
 '2019',
 '2014',
 '2019',
 '2018',
 '2022',
 '2016',
 '2021',
 '2019',
 '2019',
 '2021',
 '2019',
 '2019',
 '2018',
 '2015',
 '2020',
 '2019',
 '2017',
 '2016',
 '2020',
 '2019',
 '2018',
 '2016',
 '2019',
 '2019',
 '2022',
 '2015',
 '2015',
 '2021',
 '2017',
 '2021',
 '2019',
 '2017',
 '2015',
 '2018',
 '2018',
 '2019',
 '2017',
 '2019',
 '2019',
 '2019',
 '2016',
 '2020',
 '2016',
 '2015',
 '2021',
 '2016',
 '2016',
 '2018',
 '2019',
 '2020',
 '2021',
 '2020',
 '2018',
 '2019',
 '2021',
 '2015',
 '2017',
 '2019',
 '2020',
 '2017',
 '2020',
 '2020',
 '2019',
 '2017',
 '2017',
 '2016',
 '2018',
 '2019',
 '2021',
 '2018',
 '2019',
 '2021',
 '2018',
 '2018',
 '2019',
 '2020',
 '2017',
 '2015',
 '2019',
 '2016',
 '2016',
 '2019',
 '2018',
 '2020',
 '2019',
 '2018',
 '2016',
 '2017',
 '2018',
 '2018',
 '2015',
 '2018',
 '2019',
 '2019',
 '2018',
 '2021',
 '2018',
 '2019',
 '2014',
 '2017',
 '2016',
 '2016',
 '2017',
 '2019',
 '2020',
 '2020',
 '2018',
 '2019',
 '2019',
 '2019',
 '2018',
 '2017',
 '2017',
 '2020',
 '2022',
 '2017',
 '2018',
 '2020',
 '2018',
 '2017',
 '2019',
 '2019',
 '2018',
 '2018',
 '2020',
 '2020',
 '2018',
 '2018',
 '2018',
 '2020',
 '2018',
 '2019',
 '2021',
 '2017',
 '2016',
 '2018',
 '2018',
 '2019',
 '2018',
 '2018',
 '2018',
 '2019',
 '2017',
 '2012',
 '2016',
 '2020',
 '2022',
 '2022',
 '2019',
 '2018',
 '2019',
 '2019',
 '2014',
 '2015',
 '2014',
 '2018',
 '2019',
 '2017',
 '2019',
 '2017',
 '2017',
 '2017',
 '2019',
 '2020',
 '2019',
 '2019',
 '2019',
 '2019',
 '2020',
 '2018',
 '2016',
 '2018',
 '2017',
 '2018',
 '2020',
 '2016',
 '2017',
 '2014',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2019',
 '2018',
 '2020',
 '2021',
 '2018',
 '2019',
 '2018',
 '2017',
 '2018',
 '2018',
 '2017',
 '2018',
 '2021',
 '2018',
 '2018',
 '2019',
 '2019',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2019',
 '2015',
 '2018',
 '2018',
 '2019',
 '2017',
 '2018',
 '2016',
 ...]

In [38]:
#scrapping Transmission
Transmission=[]
try:
    Transmission_tag=driver.find_elements(By.XPATH,'//div[@class="_1jpRU"]/p/span')
    for j in Transmission_tag:
        Transmission.append(j.text)
except NoSuchElementException : #handling no such element exception
    Transmission.append('-')

In [39]:
#Number of data scrapped
len(Transmission)

1080

In [40]:
#printing Year
Transmission

['Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Automatic',
 'Automatic',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 '',
 'Manual',
 '',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Automatic',
 'Automatic',
 'Manual',
 'Automatic',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 '',
 'Manual',
 'Manual',
 'Automatic',
 'Automatic',
 'Manual',
 'Automatic',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 '',
 'Automatic',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Automatic',
 'Automatic',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Automatic',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 '',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Automatic',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Automatic',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 '',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Automatic',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Automatic',
 'Automatic',
 'Manual',
 '',
 'Automatic',
 '',
 'Automatic',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 '',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 '',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 '',
 '',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Automatic',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Automatic',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Automatic',
 '',
 'Manual',
 'Automatic',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 '',
 '',
 '',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 '',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Automatic',
 'Automatic',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Automatic',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Automatic',
 '',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Automatic',
 'Automatic',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 'Manual',
 '',
 'Manual',
 'Manual',
 'Automatic',
 'Manual',
 ...]

# Location: New Delhi

In [130]:
#scrapping Brand
Brand=[]
try:
    Brand_tag=driver.find_elements(By.XPATH,'//h3[@class="_3FpCg"]')
    for j in Brand_tag:
        Brand.append(j.text.split(' ')[1])
except NoSuchElementException : #handling no such element exception
    Brand.append('-') 
    
#scrapping Model
Model=[]
try:
    Model_tag=driver.find_elements(By.XPATH,'//h3[@class="_3FpCg"]')
    for j in Model_tag:
        Model.append(j.text.split(' ')[2:])
except NoSuchElementException : #handling no such element exception
    Model.append('-')  
    
#scrapping Year
Year=[]
try:
    Year_tag=driver.find_elements(By.XPATH,'//h3[@class="_3FpCg"]')
    for j in Year_tag:
        Year.append(j.text.split(' ')[0])
except NoSuchElementException : #handling no such element exception
    Year.append('-')  
    
#scrapping Transmission
Transmission=[]
try:
    Transmission_tag=driver.find_elements(By.XPATH,'//div[@class="_1jpRU"]/p/span')
    for j in Transmission_tag:
        Transmission.append(j.text)
except NoSuchElementException : #handling no such element exception
    Transmission.append('-')
    
#scrapping Kms driven
Kms_driven=[]
try:
    Kms_driven_tag=driver.find_elements(By.XPATH,'//ul[@class="bVR0c"]/li[1]')
    for j in Kms_driven_tag:
        Kms_driven.append(j.text)
except NoSuchElementException : #handling no such element exception
    Kms_driven.append('-')
    
#scrapping Owners
Owners=[]
try:
    Owners_tag=driver.find_elements(By.XPATH,'//ul[@class="bVR0c"]/li[2]')
    for j in Owners_tag:
        Owners.append(j.text)
except NoSuchElementException : #handling no such element exception
    Owners.append('-')
    
#scrapping Fuel type
Fuel_type=[]
try:
    Fuel_type_tag=driver.find_elements(By.XPATH,'//ul[@class="bVR0c"]/li[3]')
    for j in Fuel_type_tag:
        Fuel_type.append(j.text)
except NoSuchElementException : #handling no such element exception
    Fuel_type.append('-')
    
#scrapping Price
Price=[]
try:
    Price_tag=driver.find_elements(By.XPATH,'//div[@class="_7udZZ"]/span')
    for j in Price_tag:
        Price.append(j.text)
except NoSuchElementException : #handling no such element exception
    Price.append('-')

In [131]:
#scrapping Location
Location=[]
try:
    Location_tag=driver.find_elements(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p')
    for j in Location_tag:
        Location.append(j.text)
except NoSuchElementException : #handling no such element exception
    Location.append('-')

In [132]:
#Printing Location
Location

['New Delhi']

In [133]:
#multiplying  the Location with total number of data
Location=Location*1176

In [134]:
#printing length of each data
print(len(Brand),len(Model),len(Year),len(Transmission),len(Kms_driven),len(Owners),len(Fuel_type),len(Price),len(Location))

1176 1176 1176 1176 1176 1176 1176 1176 1176

In [135]:
#making dataframe
delhi_used_cars=pd.DataFrame()
delhi_used_cars['Brand']=Brand
delhi_used_cars['Model']=Model
delhi_used_cars['Year']=Year
delhi_used_cars['Transmission']=Transmission
delhi_used_cars['Kms_driven']=Kms_driven
delhi_used_cars['Owners']=Owners
delhi_used_cars['Fuel_type']=Fuel_type
delhi_used_cars['Location']=Location
delhi_used_cars['Price']=Price
delhi_used_cars

,Brand,Model,Year,Transmission,Kms_driven,Owners,Fuel_type,Location,Price
0,Maruti,[Swift],2020,Manual,"22,826 km",1st Owner,Petrol,New Delhi,"₹5,22,000"
1,KIA,[SELTOS],2020,Manual,"5,999 km",1st Owner,Petrol,New Delhi,"₹17,22,000"
2,Maruti,[Swift],2020,Manual,"16,691 km",2nd Owner,Petrol,New Delhi,"₹5,30,000"
3,KIA,[SELTOS],2020,Automatic,"9,417 km",1st Owner,Petrol,New Delhi,"₹16,81,000"
4,Hyundai,"[Grand, i10]",2019,Manual,"19,964 km",1st Owner,Petrol,New Delhi,"₹5,03,000"
...,...,...,...,...,...,...,...,...,...
1171,Maruti,[Swift],2011,Manual,"73,738 km",2nd Owner,Petrol,New Delhi,"₹2,70,000"
1172,Honda,[City],2013,Manual,"32,933 km",1st Owner,Petrol,New Delhi,"₹4,76,000"
1173,Honda,[Brio],2014,Automatic,"50,449 km",2nd Owner,Petrol,New Delhi,"₹3,68,000"
1174,Maruti,[Swift],2010,Manual,"32,035 km",1st Owner,Petrol,New Delhi,"₹1,92,000"
1175,Tata,[Tiago],2019,Manual,"47,017 km",2nd Owner,Diesel,New Delhi,"₹4,17,000"

In [136]:
#Saving file to excel file
delhi_used_cars.to_excel('delhi_used_cars.xlsx')

# Location:Mumbai

In [54]:
#changing location from New Delhi to Mumbai
new_delhi=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p')
new_delhi.click()

In [55]:
#clicking on Mumbai
mumbai=driver.find_element(By.XPATH,'/html/body/div[1]/div[6]/div/div/div/div/div[2]/ul/li[2]')
mumbai.click()

In [137]:
#scrapping Brand
Brand=[]
try:
    Brand_tag=driver.find_elements(By.XPATH,'//h3[@class="_3FpCg"]')
    for j in Brand_tag:
        Brand.append(j.text.split(' ')[1])
except NoSuchElementException : #handling no such element exception
    Brand.append('-') 
    
#scrapping Model
Model=[]
try:
    Model_tag=driver.find_elements(By.XPATH,'//h3[@class="_3FpCg"]')
    for j in Model_tag:
        Model.append(j.text.split(' ')[2:])
except NoSuchElementException : #handling no such element exception
    Model.append('-')  
    
#scrapping Year
Year=[]
try:
    Year_tag=driver.find_elements(By.XPATH,'//h3[@class="_3FpCg"]')
    for j in Year_tag:
        Year.append(j.text.split(' ')[0])
except NoSuchElementException : #handling no such element exception
    Year.append('-')  
    
#scrapping Transmission
Transmission=[]
try:
    Transmission_tag=driver.find_elements(By.XPATH,'//div[@class="_1jpRU"]/p/span')
    for j in Transmission_tag:
        Transmission.append(j.text)
except NoSuchElementException : #handling no such element exception
    Transmission.append('-')
    
#scrapping Kms driven
Kms_driven=[]
try:
    Kms_driven_tag=driver.find_elements(By.XPATH,'//ul[@class="bVR0c"]/li[1]')
    for j in Kms_driven_tag:
        Kms_driven.append(j.text)
except NoSuchElementException : #handling no such element exception
    Kms_driven.append('-')
    
#scrapping Owners
Owners=[]
try:
    Owners_tag=driver.find_elements(By.XPATH,'//ul[@class="bVR0c"]/li[2]')
    for j in Owners_tag:
        Owners.append(j.text)
except NoSuchElementException : #handling no such element exception
    Owners.append('-')
    
#scrapping Fuel type
Fuel_type=[]
try:
    Fuel_type_tag=driver.find_elements(By.XPATH,'//ul[@class="bVR0c"]/li[3]')
    for j in Fuel_type_tag:
        Fuel_type.append(j.text)
except NoSuchElementException : #handling no such element exception
    Fuel_type.append('-')
    
#scrapping Price
Price=[]
try:
    Price_tag=driver.find_elements(By.XPATH,'//div[@class="_7udZZ"]/span')
    for j in Price_tag:
        Price.append(j.text)
except NoSuchElementException : #handling no such element exception
    Price.append('-')

In [138]:
#scrapping Location
Location=[]
try:
    Location_tag=driver.find_elements(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p')
    for j in Location_tag:
        Location.append(j.text)
except NoSuchElementException : #handling no such element exception
    Location.append('-')

In [139]:
#Printing Location
Location

['Mumbai']

In [140]:
#multiplying  the Location with total number of data
Location=Location*651

In [141]:
#printing length of each data
print(len(Brand),len(Model),len(Year),len(Transmission),len(Kms_driven),len(Owners),len(Fuel_type),len(Price),len(Location))

651 651 651 651 651 651 651 651 651

In [142]:
#making dataframe
mumbai_used_cars=pd.DataFrame()
mumbai_used_cars['Brand']=Brand
mumbai_used_cars['Model']=Model
mumbai_used_cars['Year']=Year
mumbai_used_cars['Transmission']=Transmission
mumbai_used_cars['Kms_driven']=Kms_driven
mumbai_used_cars['Owners']=Owners
mumbai_used_cars['Fuel_type']=Fuel_type
mumbai_used_cars['Location']=Location
mumbai_used_cars['Price']=Price
mumbai_used_cars

,Brand,Model,Year,Transmission,Kms_driven,Owners,Fuel_type,Location,Price
0,Renault,[Pulse],2012,Manual,"67,241 km",2nd Owner,Diesel,Mumbai,"₹2,32,000"
1,Maruti,"[Wagon, R, 1.0]",2017,Manual,"87,260 km",1st Owner,CNG,Mumbai,"₹3,72,000"
2,Ford,[FREESTYLE],2019,Manual,"15,687 km",1st Owner,Petrol,Mumbai,"₹5,34,000"
3,Ford,[Ecosport],2016,Manual,"46,122 km",2nd Owner,Petrol,Mumbai,"₹5,37,000"
4,Hyundai,[i20],2014,Manual,"71,429 km",1st Owner,Petrol,Mumbai,"₹3,64,000"
...,...,...,...,...,...,...,...,...,...
646,Maruti,[Swift],2017,Manual,"53,005 km",1st Owner,Petrol,Mumbai,"₹4,93,000"
647,Hyundai,[ALCAZAR],2021,,"20,787 km",1st Owner,Diesel,Mumbai,"₹17,25,000"
648,Maruti,[Swift],2013,Manual,"50,702 km",2nd Owner,Petrol,Mumbai,"₹3,49,000"
649,Maruti,"[Wagon, R, 1.0]",2013,Manual,"72,289 km",3rd Owner,CNG,Mumbai,"₹3,00,000"
650,Skoda,[Rapid],2016,Manual,"17,361 km",1st Owner,Petrol,Mumbai,"₹5,91,000"

In [143]:
#Saving file to excel file
mumbai_used_cars.to_excel('mumbai_used_cars.xlsx')

# Location:Bangalore

In [74]:
#changing location from Mumbai to Bangalore
mumbai=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p')
mumbai.click()

In [75]:
#clicking on Bangalore
bangalore=driver.find_element(By.XPATH,'/html/body/div[1]/div[6]/div/div/div/div/div[2]/ul/li[3]')
bangalore.click()

In [83]:
#scrapping Brand
Brand=[]
try:
    Brand_tag=driver.find_elements(By.XPATH,'//h3[@class="_3FpCg"]')
    for j in Brand_tag:
        Brand.append(j.text.split(' ')[1])
except NoSuchElementException : #handling no such element exception
    Brand.append('-') 
    
#scrapping Model
Model=[]
try:
    Model_tag=driver.find_elements(By.XPATH,'//h3[@class="_3FpCg"]')
    for j in Model_tag:
        Model.append(j.text.split(' ')[2:])
except NoSuchElementException : #handling no such element exception
    Model.append('-')  
    
#scrapping Year
Year=[]
try:
    Year_tag=driver.find_elements(By.XPATH,'//h3[@class="_3FpCg"]')
    for j in Year_tag:
        Year.append(j.text.split(' ')[0])
except NoSuchElementException : #handling no such element exception
    Year.append('-')  
    
#scrapping Transmission
Transmission=[]
try:
    Transmission_tag=driver.find_elements(By.XPATH,'//div[@class="_1jpRU"]/p/span')
    for j in Transmission_tag:
        Transmission.append(j.text)
except NoSuchElementException : #handling no such element exception
    Transmission.append('-')
    
#scrapping Kms driven
Kms_driven=[]
try:
    Kms_driven_tag=driver.find_elements(By.XPATH,'//ul[@class="bVR0c"]/li[1]')
    for j in Kms_driven_tag:
        Kms_driven.append(j.text)
except NoSuchElementException : #handling no such element exception
    Kms_driven.append('-')
    
#scrapping Owners
Owners=[]
try:
    Owners_tag=driver.find_elements(By.XPATH,'//ul[@class="bVR0c"]/li[2]')
    for j in Owners_tag:
        Owners.append(j.text)
except NoSuchElementException : #handling no such element exception
    Owners.append('-')
    
#scrapping Fuel type
Fuel_type=[]
try:
    Fuel_type_tag=driver.find_elements(By.XPATH,'//ul[@class="bVR0c"]/li[3]')
    for j in Fuel_type_tag:
        Fuel_type.append(j.text)
except NoSuchElementException : #handling no such element exception
    Fuel_type.append('-')
    
#scrapping Price
Price=[]
try:
    Price_tag=driver.find_elements(By.XPATH,'//div[@class="_7udZZ"]/span')
    for j in Price_tag:
        Price.append(j.text)
except NoSuchElementException : #handling no such element exception
    Price.append('-')

In [77]:
#scrapping Location
Location=[]
try:
    Location_tag=driver.find_elements(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p')
    for j in Location_tag:
        Location.append(j.text)
except NoSuchElementException : #handling no such element exception
    Location.append('-')

In [78]:
#Printing Location
Location

['Bangalore']

In [80]:
#multiplying  the Location with total number of data
Location=Location*1000

In [84]:
#printing length of each data
print(len(Brand),len(Model),len(Year),len(Transmission),len(Kms_driven),len(Owners),len(Fuel_type),len(Price),len(Location))

1000 1000 1000 1000 1000 1000 1000 1000 1000

In [87]:
#making dataframe
bangalore_used_cars=pd.DataFrame()
bangalore_used_cars['Brand']=Brand
bangalore_used_cars['Model']=Model
bangalore_used_cars['Year']=Year
bangalore_used_cars['Transmission']=Transmission
bangalore_used_cars['Kms_driven']=Kms_driven
bangalore_used_cars['Owners']=Owners
bangalore_used_cars['Fuel_type']=Fuel_type
bangalore_used_cars['Location']=Location
bangalore_used_cars['Price']=Price
bangalore_used_cars

,Brand,Model,Year,Transmission,Kms_driven,Owners,Fuel_type,Location,Price
0,Toyota,"[Etios, Liva]",2013,Manual,"46,214 km",1st Owner,Petrol,Bangalore,"₹5,16,000"
1,Hyundai,[Verna],2014,Automatic,"69,232 km",2nd Owner,Diesel,Bangalore,"₹7,34,000"
2,Renault,[Kwid],2021,Manual,"7,998 km",1st Owner,Petrol,Bangalore,"₹5,67,000"
3,Volkswagen,[Polo],2011,Manual,"93,764 km",2nd Owner,Petrol,Bangalore,"₹3,82,000"
4,Honda,[Civic],2010,Manual,"78,442 km",2nd Owner,Petrol,Bangalore,"₹3,90,000"
...,...,...,...,...,...,...,...,...,...
995,Toyota,[YARIS],2018,Manual,"24,697 km",1st Owner,Petrol,Bangalore,"₹8,25,000"
996,Maruti,[Baleno],2020,,"7,040 km",1st Owner,Petrol,Bangalore,"₹8,85,000"
997,Ford,[Ecosport],2015,Manual,"68,006 km",2nd Owner,Petrol,Bangalore,"₹6,51,000"
998,Maruti,[Swift],2017,Manual,"78,247 km",1st Owner,Petrol,Bangalore,"₹6,58,000"
999,Hyundai,"[Grand, i10]",2018,Manual,"27,979 km",1st Owner,Petrol,Bangalore,"₹5,87,000"

In [88]:
#Saving file to excel file
bangalore_used_cars.to_excel('bangalore_used_cars.xlsx')

# Location: Hyderabad

In [89]:
#changing location from Bangalore to Hyderabad
bangalore=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p')
bangalore.click()

In [90]:
#clicking on Hyderabad
hyderabad=driver.find_element(By.XPATH,'/html/body/div[1]/div[6]/div/div/div/div/div[2]/ul/li[4]')
hyderabad.click()

In [91]:
#scrapping Brand
Brand=[]
try:
    Brand_tag=driver.find_elements(By.XPATH,'//h3[@class="_3FpCg"]')
    for j in Brand_tag:
        Brand.append(j.text.split(' ')[1])
except NoSuchElementException : #handling no such element exception
    Brand.append('-') 
    
#scrapping Model
Model=[]
try:
    Model_tag=driver.find_elements(By.XPATH,'//h3[@class="_3FpCg"]')
    for j in Model_tag:
        Model.append(j.text.split(' ')[2:])
except NoSuchElementException : #handling no such element exception
    Model.append('-')  
    
#scrapping Year
Year=[]
try:
    Year_tag=driver.find_elements(By.XPATH,'//h3[@class="_3FpCg"]')
    for j in Year_tag:
        Year.append(j.text.split(' ')[0])
except NoSuchElementException : #handling no such element exception
    Year.append('-')  
    
#scrapping Transmission
Transmission=[]
try:
    Transmission_tag=driver.find_elements(By.XPATH,'//div[@class="_1jpRU"]/p/span')
    for j in Transmission_tag:
        Transmission.append(j.text)
except NoSuchElementException : #handling no such element exception
    Transmission.append('-')
    
#scrapping Kms driven
Kms_driven=[]
try:
    Kms_driven_tag=driver.find_elements(By.XPATH,'//ul[@class="bVR0c"]/li[1]')
    for j in Kms_driven_tag:
        Kms_driven.append(j.text)
except NoSuchElementException : #handling no such element exception
    Kms_driven.append('-')
    
#scrapping Owners
Owners=[]
try:
    Owners_tag=driver.find_elements(By.XPATH,'//ul[@class="bVR0c"]/li[2]')
    for j in Owners_tag:
        Owners.append(j.text)
except NoSuchElementException : #handling no such element exception
    Owners.append('-')
    
#scrapping Fuel type
Fuel_type=[]
try:
    Fuel_type_tag=driver.find_elements(By.XPATH,'//ul[@class="bVR0c"]/li[3]')
    for j in Fuel_type_tag:
        Fuel_type.append(j.text)
except NoSuchElementException : #handling no such element exception
    Fuel_type.append('-')
    
#scrapping Price
Price=[]
try:
    Price_tag=driver.find_elements(By.XPATH,'//div[@class="_7udZZ"]/span')
    for j in Price_tag:
        Price.append(j.text)
except NoSuchElementException : #handling no such element exception
    Price.append('-')

In [92]:
#scrapping Location
Location=[]
try:
    Location_tag=driver.find_elements(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p')
    for j in Location_tag:
        Location.append(j.text)
except NoSuchElementException : #handling no such element exception
    Location.append('-')

In [93]:
#Printing Location
Location

['Hyderabad']

In [94]:
#multiplying  the Location with total number of data
Location=Location*548

In [95]:
#printing length of each data
print(len(Brand),len(Model),len(Year),len(Transmission),len(Kms_driven),len(Owners),len(Fuel_type),len(Price),len(Location))

548 548 548 548 548 548 548 548 548

In [96]:
#making dataframe
hyderabad_used_cars=pd.DataFrame()
hyderabad_used_cars['Brand']=Brand
hyderabad_used_cars['Model']=Model
hyderabad_used_cars['Year']=Year
hyderabad_used_cars['Transmission']=Transmission
hyderabad_used_cars['Kms_driven']=Kms_driven
hyderabad_used_cars['Owners']=Owners
hyderabad_used_cars['Fuel_type']=Fuel_type
hyderabad_used_cars['Location']=Location
hyderabad_used_cars['Price']=Price
hyderabad_used_cars

,Brand,Model,Year,Transmission,Kms_driven,Owners,Fuel_type,Location,Price
0,Renault,[Kwid],2016,Manual,"71,710 km",1st Owner,Petrol,Hyderabad,"₹3,04,000"
1,Skoda,[Rapid],2021,Automatic,"39,492 km",1st Owner,Petrol,Hyderabad,"₹10,97,000"
2,Hyundai,[Verna],2018,Manual,"66,809 km",1st Owner,Petrol,Hyderabad,"₹7,30,000"
3,Hyundai,[i10],2011,,"61,327 km",2nd Owner,Petrol,Hyderabad,"₹2,77,000"
4,Toyota,[Etios],2013,Manual,"96,919 km",1st Owner,Diesel,Hyderabad,"₹4,08,000"
...,...,...,...,...,...,...,...,...,...
543,Hyundai,[Eon],2017,Manual,0 km,1st Owner,Petrol,Hyderabad,"₹2,94,000"
544,Maruti,"[New, Wagon-R]",2021,,"51,781 km",1st Owner,Petrol,Hyderabad,"₹5,62,000"
545,Maruti,[Baleno],2015,Manual,"66,645 km",1st Owner,Petrol,Hyderabad,"₹5,68,000"
546,Ford,[Ecosport],2015,Manual,"54,425 km",1st Owner,Petrol,Hyderabad,"₹6,38,000"
547,Maruti,[Baleno],2019,Automatic,"58,713 km",1st Owner,Petrol,Hyderabad,"₹7,84,000"

In [97]:
#Saving file to excel file
hyderabad_used_cars.to_excel('hyderabad_used_cars.xlsx')

# Location: Ahmedabad

In [98]:
#changing location from Hyderabad to Ahmedabad
hyderabad=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p')
hyderabad.click()

In [99]:
#clicking on Ahmedabad
ahmedabad=driver.find_element(By.XPATH,'/html/body/div[1]/div[6]/div/div/div/div/div[2]/ul/li[5]')
ahmedabad.click()

In [102]:
#scrapping Brand
Brand=[]
try:
    Brand_tag=driver.find_elements(By.XPATH,'//h3[@class="_3FpCg"]')
    for j in Brand_tag:
        Brand.append(j.text.split(' ')[1])
except NoSuchElementException : #handling no such element exception
    Brand.append('-') 
    
#scrapping Model
Model=[]
try:
    Model_tag=driver.find_elements(By.XPATH,'//h3[@class="_3FpCg"]')
    for j in Model_tag:
        Model.append(j.text.split(' ')[2:])
except NoSuchElementException : #handling no such element exception
    Model.append('-')  
    
#scrapping Year
Year=[]
try:
    Year_tag=driver.find_elements(By.XPATH,'//h3[@class="_3FpCg"]')
    for j in Year_tag:
        Year.append(j.text.split(' ')[0])
except NoSuchElementException : #handling no such element exception
    Year.append('-')  
    
#scrapping Transmission
Transmission=[]
try:
    Transmission_tag=driver.find_elements(By.XPATH,'//div[@class="_1jpRU"]/p/span')
    for j in Transmission_tag:
        Transmission.append(j.text)
except NoSuchElementException : #handling no such element exception
    Transmission.append('-')
    
#scrapping Kms driven
Kms_driven=[]
try:
    Kms_driven_tag=driver.find_elements(By.XPATH,'//ul[@class="bVR0c"]/li[1]')
    for j in Kms_driven_tag:
        Kms_driven.append(j.text)
except NoSuchElementException : #handling no such element exception
    Kms_driven.append('-')
    
#scrapping Owners
Owners=[]
try:
    Owners_tag=driver.find_elements(By.XPATH,'//ul[@class="bVR0c"]/li[2]')
    for j in Owners_tag:
        Owners.append(j.text)
except NoSuchElementException : #handling no such element exception
    Owners.append('-')
    
#scrapping Fuel type
Fuel_type=[]
try:
    Fuel_type_tag=driver.find_elements(By.XPATH,'//ul[@class="bVR0c"]/li[3]')
    for j in Fuel_type_tag:
        Fuel_type.append(j.text)
except NoSuchElementException : #handling no such element exception
    Fuel_type.append('-')
    
#scrapping Price
Price=[]
try:
    Price_tag=driver.find_elements(By.XPATH,'//div[@class="_7udZZ"]/span')
    for j in Price_tag:
        Price.append(j.text)
except NoSuchElementException : #handling no such element exception
    Price.append('-')

In [103]:
#scrapping Location
Location=[]
try:
    Location_tag=driver.find_elements(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p')
    for j in Location_tag:
        Location.append(j.text)
except NoSuchElementException : #handling no such element exception
    Location.append('-')

In [104]:
#Printing Location
Location

['Ahmedabad']

In [105]:
#multiplying  the Location with total number of data
Location=Location*398

In [106]:
#printing length of each data
print(len(Brand),len(Model),len(Year),len(Transmission),len(Kms_driven),len(Owners),len(Fuel_type),len(Price),len(Location))

418 418 418 418 418 418 418 418 398

In [108]:
#making dataframe
ahmedabad_used_cars=pd.DataFrame()
ahmedabad_used_cars['Brand']=Brand[:398]
ahmedabad_used_cars['Model']=Model[:398]
ahmedabad_used_cars['Year']=Year[:398]
ahmedabad_used_cars['Transmission']=Transmission[:398]
ahmedabad_used_cars['Kms_driven']=Kms_driven[:398]
ahmedabad_used_cars['Owners']=Owners[:398]
ahmedabad_used_cars['Fuel_type']=Fuel_type[:398]
ahmedabad_used_cars['Location']=Location[:398]
ahmedabad_used_cars['Price']=Price[:398]
ahmedabad_used_cars

,Brand,Model,Year,Transmission,Kms_driven,Owners,Fuel_type,Location,Price
0,Maruti,[Alto],2019,Manual,"13,933 km",1st Owner,Petrol,Ahmedabad,"₹3,60,000"
1,Maruti,[Swift],2020,Manual,"58,180 km",1st Owner,Petrol,Ahmedabad,"₹6,46,000"
2,Nissan,[MAGNITE],2021,,"11,353 km",1st Owner,Petrol,Ahmedabad,"₹6,13,000"
3,Maruti,[Alto],2021,Manual,"33,066 km",1st Owner,CNG,Ahmedabad,"₹4,40,500"
4,Maruti,[Baleno],2016,Manual,"69,730 km",1st Owner,Petrol,Ahmedabad,"₹5,15,000"
...,...,...,...,...,...,...,...,...,...
393,Maruti,[Swift],2011,Manual,"53,025 km",1st Owner,Petrol,Ahmedabad,"₹3,09,000"
394,Maruti,[Eeco],2020,Manual,"30,504 km",1st Owner,Petrol,Ahmedabad,"₹4,94,000"
395,Hyundai,[i20],2012,Manual,"72,112 km",1st Owner,Petrol,Ahmedabad,"₹3,56,000"
396,Maruti,[Dzire],2018,Manual,"62,103 km",2nd Owner,Diesel,Ahmedabad,"₹6,78,000"
397,Maruti,[Eeco],2019,Manual,"12,537 km",2nd Owner,Petrol,Ahmedabad,"₹5,06,000"

In [109]:
#Saving file to excel file
ahmedabad_used_cars.to_excel('ahmedabad_used_cars.xlsx')

# Location: Gurgaon

In [110]:
#changing location from Ahmedabad to Gurgaon
Ahmedabad=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p')
Ahmedabad.click()

In [111]:
#clicking on Gurgaon
gurgaon=driver.find_element(By.XPATH,'/html/body/div[1]/div[6]/div/div/div/div/div[2]/ul/li[6]')
gurgaon.click()

In [112]:
#scrapping Brand
Brand=[]
try:
    Brand_tag=driver.find_elements(By.XPATH,'//h3[@class="_3FpCg"]')
    for j in Brand_tag:
        Brand.append(j.text.split(' ')[1])
except NoSuchElementException : #handling no such element exception
    Brand.append('-') 
    
#scrapping Model
Model=[]
try:
    Model_tag=driver.find_elements(By.XPATH,'//h3[@class="_3FpCg"]')
    for j in Model_tag:
        Model.append(j.text.split(' ')[2:])
except NoSuchElementException : #handling no such element exception
    Model.append('-')  
    
#scrapping Year
Year=[]
try:
    Year_tag=driver.find_elements(By.XPATH,'//h3[@class="_3FpCg"]')
    for j in Year_tag:
        Year.append(j.text.split(' ')[0])
except NoSuchElementException : #handling no such element exception
    Year.append('-')  
    
#scrapping Transmission
Transmission=[]
try:
    Transmission_tag=driver.find_elements(By.XPATH,'//div[@class="_1jpRU"]/p/span')
    for j in Transmission_tag:
        Transmission.append(j.text)
except NoSuchElementException : #handling no such element exception
    Transmission.append('-')
    
#scrapping Kms driven
Kms_driven=[]
try:
    Kms_driven_tag=driver.find_elements(By.XPATH,'//ul[@class="bVR0c"]/li[1]')
    for j in Kms_driven_tag:
        Kms_driven.append(j.text)
except NoSuchElementException : #handling no such element exception
    Kms_driven.append('-')
    
#scrapping Owners
Owners=[]
try:
    Owners_tag=driver.find_elements(By.XPATH,'//ul[@class="bVR0c"]/li[2]')
    for j in Owners_tag:
        Owners.append(j.text)
except NoSuchElementException : #handling no such element exception
    Owners.append('-')
    
#scrapping Fuel type
Fuel_type=[]
try:
    Fuel_type_tag=driver.find_elements(By.XPATH,'//ul[@class="bVR0c"]/li[3]')
    for j in Fuel_type_tag:
        Fuel_type.append(j.text)
except NoSuchElementException : #handling no such element exception
    Fuel_type.append('-')
    
#scrapping Price
Price=[]
try:
    Price_tag=driver.find_elements(By.XPATH,'//div[@class="_7udZZ"]/span')
    for j in Price_tag:
        Price.append(j.text)
except NoSuchElementException : #handling no such element exception
    Price.append('-')

In [113]:
#scrapping Location
Location=[]
try:
    Location_tag=driver.find_elements(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p')
    for j in Location_tag:
        Location.append(j.text)
except NoSuchElementException : #handling no such element exception
    Location.append('-')

In [114]:
#Printing Location
Location

['Gurgaon']

In [115]:
#multiplying  the Location with total number of data
Location=Location*1176

In [116]:
#printing length of each data
print(len(Brand),len(Model),len(Year),len(Transmission),len(Kms_driven),len(Owners),len(Fuel_type),len(Price),len(Location))

1176 1176 1176 1176 1176 1176 1176 1176 1176

In [117]:
#making dataframe
gurgaon_used_cars=pd.DataFrame()
gurgaon_used_cars['Brand']=Brand
gurgaon_used_cars['Model']=Model
gurgaon_used_cars['Year']=Year
gurgaon_used_cars['Transmission']=Transmission
gurgaon_used_cars['Kms_driven']=Kms_driven
gurgaon_used_cars['Owners']=Owners
gurgaon_used_cars['Fuel_type']=Fuel_type
gurgaon_used_cars['Location']=Location
gurgaon_used_cars['Price']=Price
gurgaon_used_cars

,Brand,Model,Year,Transmission,Kms_driven,Owners,Fuel_type,Location,Price
0,Hyundai,[i10],2014,Manual,"35,790 km",2nd Owner,Petrol,Gurgaon,"₹2,98,000"
1,Jeep,[Compass],2019,Automatic,"23,690 km",1st Owner,Petrol,Gurgaon,"₹19,23,000"
2,Jeep,[Compass],2019,Manual,"47,040 km",1st Owner,Diesel,Gurgaon,"₹17,06,000"
3,Skoda,[Rapid],2020,Manual,"18,953 km",1st Owner,Petrol,Gurgaon,"₹8,85,000"
4,Hyundai,[VENUE],2021,Manual,"6,059 km",1st Owner,Petrol,Gurgaon,"₹8,74,000"
...,...,...,...,...,...,...,...,...,...
1171,Maruti,[Swift],2011,Manual,"73,738 km",2nd Owner,Petrol,Gurgaon,"₹2,70,000"
1172,Honda,[Brio],2014,Automatic,"50,449 km",2nd Owner,Petrol,Gurgaon,"₹3,68,000"
1173,Honda,[City],2013,Manual,"32,933 km",1st Owner,Petrol,Gurgaon,"₹4,76,000"
1174,Maruti,[Swift],2010,Manual,"32,035 km",1st Owner,Petrol,Gurgaon,"₹1,92,000"
1175,Tata,[Tiago],2019,Manual,"47,017 km",2nd Owner,Diesel,Gurgaon,"₹4,17,000"

In [118]:
#Saving file to excel file
gurgaon_used_cars.to_excel('gurgaon_used_cars.xlsx')

# Location: Chennai

In [119]:
#changing location from Gurgaon to Chennai
gurgaon=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p')
gurgaon.click()

In [120]:
#clicking on Chennai
chennai=driver.find_element(By.XPATH,'/html/body/div[1]/div[6]/div/div/div/div/div[2]/ul/li[7]')
chennai.click()

In [121]:
#scrapping Brand
Brand=[]
try:
    Brand_tag=driver.find_elements(By.XPATH,'//h3[@class="_3FpCg"]')
    for j in Brand_tag:
        Brand.append(j.text.split(' ')[1])
except NoSuchElementException : #handling no such element exception
    Brand.append('-') 
    
#scrapping Model
Model=[]
try:
    Model_tag=driver.find_elements(By.XPATH,'//h3[@class="_3FpCg"]')
    for j in Model_tag:
        Model.append(j.text.split(' ')[2:])
except NoSuchElementException : #handling no such element exception
    Model.append('-')  
    
#scrapping Year
Year=[]
try:
    Year_tag=driver.find_elements(By.XPATH,'//h3[@class="_3FpCg"]')
    for j in Year_tag:
        Year.append(j.text.split(' ')[0])
except NoSuchElementException : #handling no such element exception
    Year.append('-')  
    
#scrapping Transmission
Transmission=[]
try:
    Transmission_tag=driver.find_elements(By.XPATH,'//div[@class="_1jpRU"]/p/span')
    for j in Transmission_tag:
        Transmission.append(j.text)
except NoSuchElementException : #handling no such element exception
    Transmission.append('-')
    
#scrapping Kms driven
Kms_driven=[]
try:
    Kms_driven_tag=driver.find_elements(By.XPATH,'//ul[@class="bVR0c"]/li[1]')
    for j in Kms_driven_tag:
        Kms_driven.append(j.text)
except NoSuchElementException : #handling no such element exception
    Kms_driven.append('-')
    
#scrapping Owners
Owners=[]
try:
    Owners_tag=driver.find_elements(By.XPATH,'//ul[@class="bVR0c"]/li[2]')
    for j in Owners_tag:
        Owners.append(j.text)
except NoSuchElementException : #handling no such element exception
    Owners.append('-')
    
#scrapping Fuel type
Fuel_type=[]
try:
    Fuel_type_tag=driver.find_elements(By.XPATH,'//ul[@class="bVR0c"]/li[3]')
    for j in Fuel_type_tag:
        Fuel_type.append(j.text)
except NoSuchElementException : #handling no such element exception
    Fuel_type.append('-')
    
#scrapping Price
Price=[]
try:
    Price_tag=driver.find_elements(By.XPATH,'//div[@class="_7udZZ"]/span')
    for j in Price_tag:
        Price.append(j.text)
except NoSuchElementException : #handling no such element exception
    Price.append('-')

In [122]:
#scrapping Location
Location=[]
try:
    Location_tag=driver.find_elements(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p')
    for j in Location_tag:
        Location.append(j.text)
except NoSuchElementException : #handling no such element exception
    Location.append('-')

In [123]:
#Printing Location
Location

['Chennai']

In [124]:
#multiplying  the Location with total number of data
Location=Location*475

In [125]:
#printing length of each data
print(len(Brand),len(Model),len(Year),len(Transmission),len(Kms_driven),len(Owners),len(Fuel_type),len(Price),len(Location))

475 475 475 475 475 475 475 475 475

In [126]:
#making dataframe
chennai_used_cars=pd.DataFrame()
chennai_used_cars['Brand']=Brand
chennai_used_cars['Model']=Model
chennai_used_cars['Year']=Year
chennai_used_cars['Transmission']=Transmission
chennai_used_cars['Kms_driven']=Kms_driven
chennai_used_cars['Owners']=Owners
chennai_used_cars['Fuel_type']=Fuel_type
chennai_used_cars['Location']=Location
chennai_used_cars['Price']=Price
chennai_used_cars

,Brand,Model,Year,Transmission,Kms_driven,Owners,Fuel_type,Location,Price
0,Volkswagen,[Vento],2015,Automatic,"61,978 km",3rd Owner,Petrol,Chennai,"₹5,47,000"
1,Tata,[NEXON],2019,Automatic,"48,266 km",1st Owner,Petrol,Chennai,"₹7,55,000"
2,Maruti,[Swift],2019,Manual,"46,592 km",2nd Owner,Diesel,Chennai,"₹6,68,000"
3,Honda,[Amaze],2019,Manual,"93,766 km",1st Owner,Diesel,Chennai,"₹6,88,000"
4,Maruti,[IGNIS],2019,Manual,"74,801 km",1st Owner,Petrol,Chennai,"₹5,38,000"
...,...,...,...,...,...,...,...,...,...
470,Hyundai,[Verna],2017,Automatic,"49,042 km",2nd Owner,Petrol,Chennai,"₹9,32,000"
471,Maruti,"[Alto, K10]",2016,Manual,"53,912 km",2nd Owner,Petrol,Chennai,"₹3,06,000"
472,Hyundai,"[Tucson, New]",2019,Automatic,"80,657 km",1st Owner,Petrol,Chennai,"₹16,79,000"
473,Maruti,[Eeco],2019,Manual,"28,706 km",1st Owner,Petrol,Chennai,"₹4,52,000"
474,Hyundai,[Eon],2017,,"25,870 km",1st Owner,Petrol,Chennai,"₹3,33,000"

In [127]:
#Saving file to excel file
chennai_used_cars.to_excel('chennai_used_cars.xlsx')

# Location: Pune

In [147]:
#changing location from Chennai to Pune
pune=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p')
pune.click()

In [148]:
#clicking on Chennai
pune=driver.find_element(By.XPATH,'/html/body/div[1]/div[6]/div/div/div/div/div[2]/ul/li[8]')
pune.click()

In [149]:
#scrapping Brand
Brand=[]
try:
    Brand_tag=driver.find_elements(By.XPATH,'//h3[@class="_3FpCg"]')
    for j in Brand_tag:
        Brand.append(j.text.split(' ')[1])
except NoSuchElementException : #handling no such element exception
    Brand.append('-') 
    
#scrapping Model
Model=[]
try:
    Model_tag=driver.find_elements(By.XPATH,'//h3[@class="_3FpCg"]')
    for j in Model_tag:
        Model.append(j.text.split(' ')[2:])
except NoSuchElementException : #handling no such element exception
    Model.append('-')  
    
#scrapping Year
Year=[]
try:
    Year_tag=driver.find_elements(By.XPATH,'//h3[@class="_3FpCg"]')
    for j in Year_tag:
        Year.append(j.text.split(' ')[0])
except NoSuchElementException : #handling no such element exception
    Year.append('-')  
    
#scrapping Transmission
Transmission=[]
try:
    Transmission_tag=driver.find_elements(By.XPATH,'//div[@class="_1jpRU"]/p/span')
    for j in Transmission_tag:
        Transmission.append(j.text)
except NoSuchElementException : #handling no such element exception
    Transmission.append('-')
    
#scrapping Kms driven
Kms_driven=[]
try:
    Kms_driven_tag=driver.find_elements(By.XPATH,'//ul[@class="bVR0c"]/li[1]')
    for j in Kms_driven_tag:
        Kms_driven.append(j.text)
except NoSuchElementException : #handling no such element exception
    Kms_driven.append('-')
    
#scrapping Owners
Owners=[]
try:
    Owners_tag=driver.find_elements(By.XPATH,'//ul[@class="bVR0c"]/li[2]')
    for j in Owners_tag:
        Owners.append(j.text)
except NoSuchElementException : #handling no such element exception
    Owners.append('-')
    
#scrapping Fuel type
Fuel_type=[]
try:
    Fuel_type_tag=driver.find_elements(By.XPATH,'//ul[@class="bVR0c"]/li[3]')
    for j in Fuel_type_tag:
        Fuel_type.append(j.text)
except NoSuchElementException : #handling no such element exception
    Fuel_type.append('-')
    
#scrapping Price
Price=[]
try:
    Price_tag=driver.find_elements(By.XPATH,'//div[@class="_7udZZ"]/span')
    for j in Price_tag:
        Price.append(j.text)
except NoSuchElementException : #handling no such element exception
    Price.append('-')

In [150]:
#scrapping Location
Location=[]
try:
    Location_tag=driver.find_elements(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p')
    for j in Location_tag:
        Location.append(j.text)
except NoSuchElementException : #handling no such element exception
    Location.append('-')

In [151]:
#Printing Location
Location

['Pune']

In [152]:
#multiplying  the Location with total number of data
Location=Location*610

In [153]:
#printing length of each data
print(len(Brand),len(Model),len(Year),len(Transmission),len(Kms_driven),len(Owners),len(Fuel_type),len(Price),len(Location))

610 610 610 610 610 610 610 610 610

In [154]:
#making dataframe
pune_used_cars=pd.DataFrame()
pune_used_cars['Brand']=Brand
pune_used_cars['Model']=Model
pune_used_cars['Year']=Year
pune_used_cars['Transmission']=Transmission
pune_used_cars['Kms_driven']=Kms_driven
pune_used_cars['Owners']=Owners
pune_used_cars['Fuel_type']=Fuel_type
pune_used_cars['Location']=Location
pune_used_cars['Price']=Price
pune_used_cars

,Brand,Model,Year,Transmission,Kms_driven,Owners,Fuel_type,Location,Price
0,Honda,[Jazz],2016,Automatic,"42,446 km",3rd Owner,Petrol,Pune,"₹4,94,000"
1,Volkswagen,[Polo],2020,,"28,405 km",1st Owner,Petrol,Pune,"₹9,25,000"
2,Hyundai,[i10],2014,,"24,876 km",1st Owner,Petrol,Pune,"₹3,91,000"
3,KIA,[SELTOS],2020,Manual,"82,756 km",1st Owner,Diesel,Pune,"₹9,97,000"
4,Tata,[NEXON],2019,Automatic,"29,264 km",2nd Owner,Diesel,Pune,"₹9,57,000"
...,...,...,...,...,...,...,...,...,...
605,Tata,[Tiago],2021,Manual,"25,468 km",1st Owner,Petrol,Pune,"₹6,84,000"
606,Tata,[NEXON],2022,,"6,593 km",1st Owner,Petrol,Pune,"₹12,06,000"
607,Maruti,[Baleno],2019,Manual,"20,240 km",1st Owner,Petrol,Pune,"₹7,64,000"
608,Tata,[Tiago],2021,Automatic,"11,446 km",1st Owner,Petrol,Pune,"₹6,86,000"
609,Tata,[NEXON],2021,Automatic,"15,053 km",1st Owner,Petrol,Pune,"₹11,15,000"

In [155]:
#Saving file to excel file
pune_used_cars.to_excel('pune_used_cars.xlsx')

In [156]:
#Concating all the dataframes
car_price_prediction=pd.concat([delhi_used_cars,mumbai_used_cars,bangalore_used_cars,hyderabad_used_cars,ahmedabad_used_cars,gurgaon_used_cars,chennai_used_cars,pune_used_cars])
car_price_prediction

,Brand,Model,Year,Transmission,Kms_driven,Owners,Fuel_type,Location,Price
0,Maruti,[Swift],2020,Manual,"22,826 km",1st Owner,Petrol,New Delhi,"₹5,22,000"
1,KIA,[SELTOS],2020,Manual,"5,999 km",1st Owner,Petrol,New Delhi,"₹17,22,000"
2,Maruti,[Swift],2020,Manual,"16,691 km",2nd Owner,Petrol,New Delhi,"₹5,30,000"
3,KIA,[SELTOS],2020,Automatic,"9,417 km",1st Owner,Petrol,New Delhi,"₹16,81,000"
4,Hyundai,"[Grand, i10]",2019,Manual,"19,964 km",1st Owner,Petrol,New Delhi,"₹5,03,000"
...,...,...,...,...,...,...,...,...,...
605,Tata,[Tiago],2021,Manual,"25,468 km",1st Owner,Petrol,Pune,"₹6,84,000"
606,Tata,[NEXON],2022,,"6,593 km",1st Owner,Petrol,Pune,"₹12,06,000"
607,Maruti,[Baleno],2019,Manual,"20,240 km",1st Owner,Petrol,Pune,"₹7,64,000"
608,Tata,[Tiago],2021,Automatic,"11,446 km",1st Owner,Petrol,Pune,"₹6,86,000"
609,Tata,[NEXON],2021,Automatic,"15,053 km",1st Owner,Petrol,Pune,"₹11,15,000"

In [157]:
#Saving file to csv
car_price_prediction.to_excel('CAR_PRICE_PREDICTION.xlsx')